-- Auto-generated FRLG Multichoice Lists from ROM gMultichoiceLists. DO NOT EDIT DIRECTLY.
return {
  [0] = { count = 2, labels = { "YES", "NO" } },
  [1] = { count = 5, labels = { "EEVEE", "FLAREON", "JOLTEON", "VAPOREON", "Quit looking." } },
  [2] = { count = 4, labels = { "NORMAL", "BLACK", "PINK", "SEPIA" } },
  [3] = { count = 2, labels = { "HALL OF FAME", "QUIT" } },
  [4] = { count = 2, labels = { "EGGS", "QUIT" } },
  [5] = { count = 2, labels = { "VICTORIES", "QUIT" } },
  [6] = { count = 3, labels = { "HALL OF FAME", "EGGS", "QUIT" } },
  [7] = { count = 3, labels = { "HALL OF FAME", "VICTORIES", "QUIT" } },
  [8] = { count = 3, labels = { "EGGS", "VICTORIES", "QUIT" } },
  [9] = { count = 4, labels = { "HALL OF FAME", "EGGS", "VICTORIES", "QUIT" } },
  [10] = { count = 1, labels = { "EXIT" } },
  [11] = { count = 1, labels = { "EXIT" } },
  [12] = { count = 1, labels = { "EXIT" } },
  [13] = { count = 2, labels = { "BICYCLE ¥1,000,000", "NO THANKS" } },
  [14] = { count = 6, labels = { "ABRA 180 COINS", "CLEFAIRY 500 COINS", "DRATINI 2,800 COINS", "SCYTHER 5,500 COINS", "PORYGON 9,999 COINS", "NO THANKS" } },
  [15] = { count = 6, labels = { "SLP", "PSN", "PAR", "BRN", "FRZ", "EXIT" } },
  [16] = { count = 3, labels = { "YES", "NO", "INFO" } },
  [17] = { count = 5, labels = { "SINGLE BATTLE", "DOUBLE BATTLE", "MULTI BATTLE", "INFO", "EXIT" } },
  [18] = { count = 3, labels = { "YES", "NO", "INFO" } },
  [19] = { count = 3, labels = { "Make a challenge.", "INFO", "EXIT" } },
  [20] = { count = 3, labels = { "ROOFTOP", "B1F", "EXIT" } },
  [21] = { count = 2, labels = { "HELIX FOSSIL", "EXIT" } },
  [22] = { count = 2, labels = { "DOME FOSSIL", "EXIT" } },
  [23] = { count = 2, labels = { "OLD AMBER", "EXIT" } },
  [24] = { count = 3, labels = { "HELIX FOSSIL", "OLD AMBER", "EXIT" } },
  [25] = { count = 3, labels = { "DOME FOSSIL", "OLD AMBER", "EXIT" } },
  [26] = { count = 4, labels = { "FRESH WATER ¥200", "SODA POP ¥300", "LEMONADE ¥350", "EXIT" } },
  [27] = { count = 3, labels = { "50 COINS ¥1,000", "500 COINS ¥10,000", "EXIT" } },
  [28] = { count = 2, labels = { "Excellent", "Not so bad" } },
  [29] = { count = 2, labels = { "Right", "Left" } },
  [30] = { count = 6, labels = { "TM13 4,000 COINS", "TM23 3,500 COINS", "TM24 4,000 COINS", "TM30 4,500 COINS", "TM35 4,000 COINS", "NO THANKS" } },
  [31] = { count = 6, labels = { "5F", "4F", "3F", "2F", "1F", "EXIT" } },
  [32] = { count = 2, labels = { "FRESH WATER", "EXIT" } },
  [33] = { count = 2, labels = { "SODA POP", "EXIT" } },
  [34] = { count = 3, labels = { "FRESH WATER", "SODA POP", "EXIT" } },
  [35] = { count = 2, labels = { "LEMONADE", "EXIT" } },
  [36] = { count = 3, labels = { "FRESH WATER", "LEMONADE", "EXIT" } },
  [37] = { count = 3, labels = { "SODA POP", "LEMONADE", "EXIT" } },
  [38] = { count = 4, labels = { "FRESH WATER", "SODA POP", "LEMONADE", "EXIT" } },
  [39] = { count = 3, labels = { "TRADE CENTER", "COLOSSEUM", "EXIT" } },
  [40] = { count = 3, labels = { "Game Link cable", "Wireless", "EXIT" } },
  [41] = { count = 6, labels = { "SMOKE BALL 800 COINS", "MIRACLE SEED 1,000 COINS", "CHARCOAL 1,000 COINS", "MYSTIC WATER 1,000 COINS", "YELLOW FLUTE 1,600 COINS", "NO THANKS" } },
  [42] = { count = 4, labels = { "B1F", "B2F", "B4F", "EXIT" } },
  [43] = { count = 4, labels = { "LINKED GAME PLAY", "DIRECT CORNER", "UNION ROOM", "QUIT" } },
  [44] = { count = 3, labels = { "TWO ISLAND", "THREE ISLAND", "EXIT" } },
  [45] = { count = 3, labels = { "ONE ISLAND", "THREE ISLAND", "EXIT" } },
  [46] = { count = 3, labels = { "ONE ISLAND", "TWO ISLAND", "EXIT" } },
  [47] = { count = 4, labels = { "TRADE CENTER", "COLOSSEUM", "BERRY CRUSH", "EXIT" } },
  [48] = { count = 3, labels = { "", "", "EXIT" } },
  [49] = { count = 3, labels = { "POKéMON JUMP", "DODRIO BERRY-PICKING", "EXIT" } },
  [50] = { count = 3, labels = { "TRADE CENTER", "COLOSSEUM", "EXIT" } },
  [51] = { count = 2, labels = { "2 TINYMUSHROOMS", "1 BIG MUSHROOM" } },
  [52] = { count = 5, labels = { "TRADE CENTER", "COLOSSEUM", "", "BERRY CRUSH", "EXIT" } },
  [53] = { count = 4, labels = { "TRADE CENTER", "COLOSSEUM", "", "EXIT" } },
  [54] = { count = 3, labels = { "SEVII ISLANDS", "NAVEL ROCK", "EXIT" } },
  [55] = { count = 3, labels = { "SEVII ISLANDS", "BIRTH ISLAND", "EXIT" } },
  [56] = { count = 4, labels = { "SEVII ISLANDS", "NAVEL ROCK", "BIRTH ISLAND", "EXIT" } },
  [57] = { count = 4, labels = { "ONE ISLAND", "TWO ISLAND", "THREE ISLAND", "EXIT" } },
  [58] = { count = 4, labels = { "VERMILION", "TWO ISLAND", "THREE ISLAND", "EXIT" } },
  [59] = { count = 4, labels = { "VERMILION", "ONE ISLAND", "THREE ISLAND", "EXIT" } },
  [60] = { count = 4, labels = { "VERMILION", "ONE ISLAND", "TWO ISLAND", "EXIT" } },
  [61] = { count = 2, labels = { "VERMILION", "EXIT" } },
  [62] = { count = 3, labels = { "", "", "EXIT" } },
  [63] = { count = 3, labels = { "JOIN GROUP", "BECOME LEADER", "EXIT" } },
  [64] = { count = 5, labels = { "SINGLE", "DOUBLE", "KNOCKOUT", "MIXED", "EXIT" } },
}
