#!/usr/bin/env python3
"""Generate src/import/gba/syms/<game>.lua and <game>_funcs.lua from a pret GBA ELF.

usage: tools/gen_gba_syms.py --game emerald --elf ../pokeemerald/pokeemerald.elf [--out-dir src/import/gba/syms]
       tools/gen_gba_syms.py --game emerald --elf ... --check
"""

import argparse
import os
import re
import subprocess
import sys

ROM_LO = 0x08000000
ROM_HI = 0x0A000000
SONG_OBJ = re.compile(r"^(mus|se|ph)_.*\.o$")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_int(text):
    return int(text, 16) if text.startswith("0x") else int(text)


def read_symbols(elf):
    out = subprocess.run(["arm-none-eabi-readelf", "-sW", elf], check=True,
                         capture_output=True, text=True).stdout
    cur_file = None
    rows = []
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 8 or not parts[0].endswith(":") or not parts[0][:-1].isdigit():
            continue
        value, size, typ, bind, _vis, ndx, name = parts[1], parts[2], parts[3], parts[4], parts[5], parts[6], parts[7]
        if typ == "FILE":
            cur_file = name
            continue
        if typ == "SECTION" or not name or name.startswith("$") or name.startswith(".L"):
            continue
        addr = int(value, 16)
        if typ == "FUNC":
            addr &= ~1
        if addr < ROM_LO or addr >= ROM_HI:
            continue
        local = bind == "LOCAL"
        obj = cur_file if local else None
        if local and typ == "NOTYPE" and obj and SONG_OBJ.match(obj):
            continue
        rows.append({
            "name": name, "off": addr - ROM_LO, "size": parse_int(size), "type": typ,
            "local": local, "obj": obj, "ndx": ndx,
        })
    return rows


def fill_spans(rows):
    by_sec = {}
    for r in rows:
        by_sec.setdefault(r["ndx"], set()).add(r["off"])
    nexts = {}
    for sec, offs in by_sec.items():
        ordered = sorted(offs)
        nexts[sec] = {ordered[i]: ordered[i + 1] for i in range(len(ordered) - 1)}
    for r in rows:
        if r["size"] == 0 and r["type"] != "FUNC":
            nxt = nexts[r["ndx"]].get(r["off"])
            r["span"] = (nxt - r["off"]) if nxt is not None else 0


def dedupe(rows):
    seen = {}
    out = []
    for r in rows:
        key = (r["name"], r["off"], r["obj"])
        if key in seen:
            continue
        seen[key] = True
        out.append(r)
    return out


def build(rows):
    rows = dedupe(rows)
    by_name = {}
    for r in rows:
        by_name.setdefault(r["name"], []).append(r)
    collide = sorted(n for n, rs in by_name.items() if len({x["off"] for x in rs}) > 1)
    collide_set = set(collide)
    objs = sorted({r["obj"] for r in rows if r["obj"]})
    obj_index = {o: i + 1 for i, o in enumerate(objs)}
    lines = []
    for name in sorted(by_name):
        rs = by_name[name]
        if name not in collide_set:
            rs = [rs[0]]
        for r in rs:
            if r["type"] == "FUNC":
                size = "%x" % r["size"]
            elif r["size"] == 0:
                size = "~%x" % r.get("span", 0)
            else:
                size = "%x" % r["size"]
            obj = str(obj_index[r["obj"]]) if r["obj"] else ""
            if name in collide_set and not r["obj"]:
                obj = "0"
            lines.append("%s %x %s %s" % (name, r["off"], size, obj) if obj else "%s %x %s" % (name, r["off"], size))
    return objs, collide, lines


def render(game, elf_name, kind, objs, collide, lines):
    head = "-- generated by tools/gen_gba_syms.py from %s, addresses only\n" % elf_name
    body = [head, "return {\n", '  game = "%s",\n' % game, '  kind = "%s",\n' % kind]
    body.append("  objs = [==[\n%s\n]==],\n" % "\n".join(objs))
    body.append("  collide = [==[\n%s\n]==],\n" % "\n".join(collide))
    body.append("  data = [==[\n%s\n]==],\n" % "\n".join(lines))
    body.append("}\n")
    return "".join(body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--game", required=True)
    ap.add_argument("--elf", required=True)
    ap.add_argument("--out-dir", default=os.path.join(ROOT, "src", "import", "gba", "syms"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rows = read_symbols(args.elf)
    fill_spans(rows)
    elf_name = os.path.basename(args.elf)
    data_rows = [r for r in rows if r["type"] != "FUNC"]
    func_rows = [r for r in rows if r["type"] == "FUNC"]
    outputs = {
        os.path.join(args.out_dir, "%s.lua" % args.game): render(args.game, elf_name, "data", *build(data_rows)),
        os.path.join(args.out_dir, "%s_funcs.lua" % args.game): render(args.game, elf_name, "func", *build(func_rows)),
    }
    status = 0
    for path, text in outputs.items():
        if args.check:
            try:
                with open(path) as f:
                    same = f.read() == text
            except OSError:
                same = False
            print("%s %s" % ("OK" if same else "DIFF", os.path.relpath(path, ROOT)))
            status |= 0 if same else 1
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(text)
            print("wrote %s (%d bytes)" % (os.path.relpath(path, ROOT), len(text)))
    return status


if __name__ == "__main__":
    sys.exit(main())
