-- Easy Chat words and group dictionaries (extracted from FireRed pret data).
-- Reference: pret/pokefirered/src/data/easy_chat/

local EasyChatData = {}

EasyChatData.EC_WORD_UNDEFINED = 0xFFFF
EasyChatData.PASSPHRASE_MYSTERY_EVENT = { 5178, 6167, 4107, 8207 } -- MYSTERY EVENT IS EXCITING
EasyChatData.PASSPHRASE_QUESTIONNAIRE = { 521, 5131, 4144, 4138 } -- LINK TOGETHER WITH ALL
EasyChatData.DEFAULT_PROFILE = { 2601, 4128, 526, 2611 } -- I AM A POKéMON FRIEND

EasyChatData.GROUPS = {
  [0] = {
    id = 0,
    name = 'POKéMON',
    words = {
      { id = 63, text = 'ABRA' },
      { id = 142, text = 'AERODACTYL' },
      { id = 190, text = 'AIPOM' },
      { id = 65, text = 'ALAKAZAM' },
      { id = 181, text = 'AMPHAROS' },
      { id = 24, text = 'ARBOK' },
      { id = 59, text = 'ARCANINE' },
      { id = 168, text = 'ARIADOS' },
      { id = 144, text = 'ARTICUNO' },
      { id = 184, text = 'AZUMARILL' },
      { id = 153, text = 'BAYLEEF' },
      { id = 15, text = 'BEEDRILL' },
      { id = 182, text = 'BELLOSSOM' },
      { id = 69, text = 'BELLSPROUT' },
      { id = 9, text = 'BLASTOISE' },
      { id = 242, text = 'BLISSEY' },
      { id = 1, text = 'BULBASAUR' },
      { id = 12, text = 'BUTTERFREE' },
      { id = 10, text = 'CATERPIE' },
      { id = 251, text = 'CELEBI' },
      { id = 113, text = 'CHANSEY' },
      { id = 6, text = 'CHARIZARD' },
      { id = 4, text = 'CHARMANDER' },
      { id = 5, text = 'CHARMELEON' },
      { id = 152, text = 'CHIKORITA' },
      { id = 170, text = 'CHINCHOU' },
      { id = 36, text = 'CLEFABLE' },
      { id = 35, text = 'CLEFAIRY' },
      { id = 173, text = 'CLEFFA' },
      { id = 91, text = 'CLOYSTER' },
      { id = 222, text = 'CORSOLA' },
      { id = 169, text = 'CROBAT' },
      { id = 159, text = 'CROCONAW' },
      { id = 104, text = 'CUBONE' },
      { id = 155, text = 'CYNDAQUIL' },
      { id = 225, text = 'DELIBIRD' },
      { id = 87, text = 'DEWGONG' },
      { id = 50, text = 'DIGLETT' },
      { id = 132, text = 'DITTO' },
      { id = 85, text = 'DODRIO' },
      { id = 84, text = 'DODUO' },
      { id = 232, text = 'DONPHAN' },
      { id = 148, text = 'DRAGONAIR' },
      { id = 149, text = 'DRAGONITE' },
      { id = 147, text = 'DRATINI' },
      { id = 96, text = 'DROWZEE' },
      { id = 51, text = 'DUGTRIO' },
      { id = 206, text = 'DUNSPARCE' },
      { id = 133, text = 'EEVEE' },
      { id = 23, text = 'EKANS' },
      { id = 125, text = 'ELECTABUZZ' },
      { id = 101, text = 'ELECTRODE' },
      { id = 239, text = 'ELEKID' },
      { id = 244, text = 'ENTEI' },
      { id = 196, text = 'ESPEON' },
      { id = 102, text = 'EXEGGCUTE' },
      { id = 103, text = 'EXEGGUTOR' },
      { id = 83, text = "FARFETCH'D" },
      { id = 22, text = 'FEAROW' },
      { id = 160, text = 'FERALIGATR' },
      { id = 180, text = 'FLAAFFY' },
      { id = 136, text = 'FLAREON' },
      { id = 205, text = 'FORRETRESS' },
      { id = 162, text = 'FURRET' },
      { id = 92, text = 'GASTLY' },
      { id = 94, text = 'GENGAR' },
      { id = 74, text = 'GEODUDE' },
      { id = 203, text = 'GIRAFARIG' },
      { id = 207, text = 'GLIGAR' },
      { id = 44, text = 'GLOOM' },
      { id = 42, text = 'GOLBAT' },
      { id = 118, text = 'GOLDEEN' },
      { id = 55, text = 'GOLDUCK' },
      { id = 76, text = 'GOLEM' },
      { id = 210, text = 'GRANBULL' },
      { id = 75, text = 'GRAVELER' },
      { id = 88, text = 'GRIMER' },
      { id = 58, text = 'GROWLITHE' },
      { id = 130, text = 'GYARADOS' },
      { id = 93, text = 'HAUNTER' },
      { id = 214, text = 'HERACROSS' },
      { id = 107, text = 'HITMONCHAN' },
      { id = 106, text = 'HITMONLEE' },
      { id = 237, text = 'HITMONTOP' },
      { id = 250, text = 'HO-OH' },
      { id = 163, text = 'HOOTHOOT' },
      { id = 187, text = 'HOPPIP' },
      { id = 116, text = 'HORSEA' },
      { id = 229, text = 'HOUNDOOM' },
      { id = 228, text = 'HOUNDOUR' },
      { id = 97, text = 'HYPNO' },
      { id = 174, text = 'IGGLYBUFF' },
      { id = 2, text = 'IVYSAUR' },
      { id = 39, text = 'JIGGLYPUFF' },
      { id = 135, text = 'JOLTEON' },
      { id = 189, text = 'JUMPLUFF' },
      { id = 124, text = 'JYNX' },
      { id = 140, text = 'KABUTO' },
      { id = 141, text = 'KABUTOPS' },
      { id = 64, text = 'KADABRA' },
      { id = 14, text = 'KAKUNA' },
      { id = 115, text = 'KANGASKHAN' },
      { id = 230, text = 'KINGDRA' },
      { id = 99, text = 'KINGLER' },
      { id = 109, text = 'KOFFING' },
      { id = 98, text = 'KRABBY' },
      { id = 171, text = 'LANTURN' },
      { id = 131, text = 'LAPRAS' },
      { id = 246, text = 'LARVITAR' },
      { id = 166, text = 'LEDIAN' },
      { id = 165, text = 'LEDYBA' },
      { id = 108, text = 'LICKITUNG' },
      { id = 249, text = 'LUGIA' },
      { id = 68, text = 'MACHAMP' },
      { id = 67, text = 'MACHOKE' },
      { id = 66, text = 'MACHOP' },
      { id = 240, text = 'MAGBY' },
      { id = 219, text = 'MAGCARGO' },
      { id = 129, text = 'MAGIKARP' },
      { id = 126, text = 'MAGMAR' },
      { id = 81, text = 'MAGNEMITE' },
      { id = 82, text = 'MAGNETON' },
      { id = 56, text = 'MANKEY' },
      { id = 226, text = 'MANTINE' },
      { id = 179, text = 'MAREEP' },
      { id = 183, text = 'MARILL' },
      { id = 105, text = 'MAROWAK' },
      { id = 154, text = 'MEGANIUM' },
      { id = 52, text = 'MEOWTH' },
      { id = 11, text = 'METAPOD' },
      { id = 151, text = 'MEW' },
      { id = 150, text = 'MEWTWO' },
      { id = 241, text = 'MILTANK' },
      { id = 200, text = 'MISDREAVUS' },
      { id = 146, text = 'MOLTRES' },
      { id = 122, text = 'MR. MIME' },
      { id = 89, text = 'MUK' },
      { id = 198, text = 'MURKROW' },
      { id = 177, text = 'NATU' },
      { id = 34, text = 'NIDOKING' },
      { id = 31, text = 'NIDOQUEEN' },
      { id = 29, text = 'NIDORAN♀' },
      { id = 32, text = 'NIDORAN♂' },
      { id = 30, text = 'NIDORINA' },
      { id = 33, text = 'NIDORINO' },
      { id = 38, text = 'NINETALES' },
      { id = 164, text = 'NOCTOWL' },
      { id = 224, text = 'OCTILLERY' },
      { id = 43, text = 'ODDISH' },
      { id = 138, text = 'OMANYTE' },
      { id = 139, text = 'OMASTAR' },
      { id = 95, text = 'ONIX' },
      { id = 46, text = 'PARAS' },
      { id = 47, text = 'PARASECT' },
      { id = 53, text = 'PERSIAN' },
      { id = 231, text = 'PHANPY' },
      { id = 172, text = 'PICHU' },
      { id = 18, text = 'PIDGEOT' },
      { id = 17, text = 'PIDGEOTTO' },
      { id = 16, text = 'PIDGEY' },
      { id = 25, text = 'PIKACHU' },
      { id = 221, text = 'PILOSWINE' },
      { id = 204, text = 'PINECO' },
      { id = 127, text = 'PINSIR' },
      { id = 186, text = 'POLITOED' },
      { id = 60, text = 'POLIWAG' },
      { id = 61, text = 'POLIWHIRL' },
      { id = 62, text = 'POLIWRATH' },
      { id = 77, text = 'PONYTA' },
      { id = 137, text = 'PORYGON' },
      { id = 233, text = 'PORYGON2' },
      { id = 57, text = 'PRIMEAPE' },
      { id = 54, text = 'PSYDUCK' },
      { id = 247, text = 'PUPITAR' },
      { id = 195, text = 'QUAGSIRE' },
      { id = 156, text = 'QUILAVA' },
      { id = 211, text = 'QWILFISH' },
      { id = 26, text = 'RAICHU' },
      { id = 243, text = 'RAIKOU' },
      { id = 78, text = 'RAPIDASH' },
      { id = 20, text = 'RATICATE' },
      { id = 19, text = 'RATTATA' },
      { id = 223, text = 'REMORAID' },
      { id = 112, text = 'RHYDON' },
      { id = 111, text = 'RHYHORN' },
      { id = 27, text = 'SANDSHREW' },
      { id = 28, text = 'SANDSLASH' },
      { id = 212, text = 'SCIZOR' },
      { id = 123, text = 'SCYTHER' },
      { id = 117, text = 'SEADRA' },
      { id = 119, text = 'SEAKING' },
      { id = 86, text = 'SEEL' },
      { id = 161, text = 'SENTRET' },
      { id = 90, text = 'SHELLDER' },
      { id = 213, text = 'SHUCKLE' },
      { id = 227, text = 'SKARMORY' },
      { id = 188, text = 'SKIPLOOM' },
      { id = 80, text = 'SLOWBRO' },
      { id = 199, text = 'SLOWKING' },
      { id = 79, text = 'SLOWPOKE' },
      { id = 218, text = 'SLUGMA' },
      { id = 235, text = 'SMEARGLE' },
      { id = 238, text = 'SMOOCHUM' },
      { id = 215, text = 'SNEASEL' },
      { id = 143, text = 'SNORLAX' },
      { id = 209, text = 'SNUBBULL' },
      { id = 21, text = 'SPEAROW' },
      { id = 167, text = 'SPINARAK' },
      { id = 7, text = 'SQUIRTLE' },
      { id = 234, text = 'STANTLER' },
      { id = 121, text = 'STARMIE' },
      { id = 120, text = 'STARYU' },
      { id = 208, text = 'STEELIX' },
      { id = 185, text = 'SUDOWOODO' },
      { id = 245, text = 'SUICUNE' },
      { id = 192, text = 'SUNFLORA' },
      { id = 191, text = 'SUNKERN' },
      { id = 220, text = 'SWINUB' },
      { id = 114, text = 'TANGELA' },
      { id = 128, text = 'TAUROS' },
      { id = 216, text = 'TEDDIURSA' },
      { id = 72, text = 'TENTACOOL' },
      { id = 73, text = 'TENTACRUEL' },
      { id = 175, text = 'TOGEPI' },
      { id = 176, text = 'TOGETIC' },
      { id = 158, text = 'TOTODILE' },
      { id = 157, text = 'TYPHLOSION' },
      { id = 248, text = 'TYRANITAR' },
      { id = 236, text = 'TYROGUE' },
      { id = 197, text = 'UMBREON' },
      { id = 201, text = 'UNOWN' },
      { id = 217, text = 'URSARING' },
      { id = 134, text = 'VAPOREON' },
      { id = 49, text = 'VENOMOTH' },
      { id = 48, text = 'VENONAT' },
      { id = 3, text = 'VENUSAUR' },
      { id = 71, text = 'VICTREEBEL' },
      { id = 45, text = 'VILEPLUME' },
      { id = 100, text = 'VOLTORB' },
      { id = 37, text = 'VULPIX' },
      { id = 8, text = 'WARTORTLE' },
      { id = 13, text = 'WEEDLE' },
      { id = 70, text = 'WEEPINBELL' },
      { id = 110, text = 'WEEZING' },
      { id = 40, text = 'WIGGLYTUFF' },
      { id = 202, text = 'WOBBUFFET' },
      { id = 194, text = 'WOOPER' },
      { id = 178, text = 'XATU' },
      { id = 193, text = 'YANMA' },
      { id = 145, text = 'ZAPDOS' },
      { id = 41, text = 'ZUBAT' },
    },
  },
  [1] = {
    id = 1,
    name = 'TRAINER',
    words = {
      { id = 512, text = 'I CHOOSE YOU' },
      { id = 513, text = 'GOTCHA' },
      { id = 514, text = 'TRADE' },
      { id = 515, text = 'SAPPHIRE' },
      { id = 516, text = 'EVOLVE' },
      { id = 517, text = 'ENCYCLOPEDIA' },
      { id = 518, text = 'NATURE' },
      { id = 519, text = 'CENTER' },
      { id = 520, text = 'EGG' },
      { id = 521, text = 'LINK' },
      { id = 522, text = 'SP. ABILITY' },
      { id = 523, text = 'TRAINER' },
      { id = 524, text = 'VERSION' },
      { id = 525, text = 'POKéNAV' },
      { id = 526, text = 'POKéMON' },
      { id = 527, text = 'GET' },
      { id = 528, text = 'POKéDEX' },
      { id = 529, text = 'RUBY' },
      { id = 530, text = 'LEVEL' },
      { id = 531, text = 'RED' },
      { id = 532, text = 'GREEN' },
      { id = 533, text = 'BAG' },
      { id = 534, text = 'FLAME' },
      { id = 535, text = 'GOLD' },
      { id = 536, text = 'LEAF' },
      { id = 537, text = 'SILVER' },
    },
  },
  [2] = {
    id = 2,
    name = 'STATUS',
    words = {
      { id = 1024, text = 'DARK' },
      { id = 1025, text = 'STENCH' },
      { id = 1026, text = 'THICK FAT' },
      { id = 1027, text = 'RAIN DISH' },
      { id = 1028, text = 'DRIZZLE' },
      { id = 1029, text = 'ARENA TRAP' },
      { id = 1030, text = 'INTIMIDATE' },
      { id = 1031, text = 'ROCK HEAD' },
      { id = 1032, text = 'COLOR' },
      { id = 1033, text = 'ALT. COLOR' },
      { id = 1034, text = 'ROCK' },
      { id = 1035, text = 'BEAUTIFUL' },
      { id = 1036, text = 'BEAUTY' },
      { id = 1037, text = 'AIR LOCK' },
      { id = 1038, text = 'PSYCHIC' },
      { id = 1039, text = 'HYPER CUTTER' },
      { id = 1040, text = 'FIGHTING' },
      { id = 1041, text = 'SHADOW TAG' },
      { id = 1042, text = 'SMART' },
      { id = 1043, text = 'SMARTNESS' },
      { id = 1044, text = 'SPEED BOOST' },
      { id = 1045, text = 'COOL' },
      { id = 1046, text = 'COOLNESS' },
      { id = 1047, text = 'BATTLE ARMOR' },
      { id = 1048, text = 'CUTE' },
      { id = 1049, text = 'CUTENESS' },
      { id = 1050, text = 'STURDY' },
      { id = 1051, text = 'SUCTION CUPS' },
      { id = 1052, text = 'GRASS' },
      { id = 1053, text = 'CLEAR BODY' },
      { id = 1054, text = 'TORRENT' },
      { id = 1055, text = 'GHOST' },
      { id = 1056, text = 'ICE' },
      { id = 1057, text = 'GUTS' },
      { id = 1058, text = 'ROUGH SKIN' },
      { id = 1059, text = 'SHELL ARMOR' },
      { id = 1060, text = 'NATURAL CURE' },
      { id = 1061, text = 'DAMP' },
      { id = 1062, text = 'GROUND' },
      { id = 1063, text = 'LIMBER' },
      { id = 1064, text = 'MAGNET PULL' },
      { id = 1065, text = 'WHITE SMOKE' },
      { id = 1066, text = 'SYNCHRONIZE' },
      { id = 1067, text = 'OVERGROW' },
      { id = 1068, text = 'SWIFT SWIM' },
      { id = 1069, text = 'SAND STREAM' },
      { id = 1070, text = 'SAND VEIL' },
      { id = 1071, text = 'KEEN EYE' },
      { id = 1072, text = 'INNER FOCUS' },
      { id = 1073, text = 'STATIC' },
      { id = 1074, text = 'TYPE' },
      { id = 1075, text = 'TOUGH' },
      { id = 1076, text = 'TOUGHNESS' },
      { id = 1077, text = 'SHED SKIN' },
      { id = 1078, text = 'HUGE POWER' },
      { id = 1079, text = 'VOLT ABSORB' },
      { id = 1080, text = 'WATER ABSORB' },
      { id = 1081, text = 'ELECTRIC' },
      { id = 1082, text = 'FORECAST' },
      { id = 1083, text = 'SERENE GRACE' },
      { id = 1084, text = 'POISON' },
      { id = 1085, text = 'POISON POINT' },
      { id = 1086, text = 'DRAGON' },
      { id = 1087, text = 'TRACE' },
      { id = 1088, text = 'OBLIVIOUS' },
      { id = 1089, text = 'TRUANT' },
      { id = 1090, text = 'RUN AWAY' },
      { id = 1091, text = 'STICKY HOLD' },
      { id = 1092, text = 'CLOUD NINE' },
      { id = 1093, text = 'NORMAL' },
      { id = 1094, text = 'STEEL' },
      { id = 1095, text = 'ILLUMINATE' },
      { id = 1096, text = 'EARLY BIRD' },
      { id = 1097, text = 'HUSTLE' },
      { id = 1098, text = 'SHINE' },
      { id = 1099, text = 'FLYING' },
      { id = 1100, text = 'DROUGHT' },
      { id = 1101, text = 'LIGHTNINGROD' },
      { id = 1102, text = 'COMPOUNDEYES' },
      { id = 1103, text = 'MARVEL SCALE' },
      { id = 1104, text = 'WONDER GUARD' },
      { id = 1105, text = 'INSOMNIA' },
      { id = 1106, text = 'LEVITATE' },
      { id = 1107, text = 'PLUS' },
      { id = 1108, text = 'PRESSURE' },
      { id = 1109, text = 'LIQUID OOZE' },
      { id = 1110, text = 'COLOR CHANGE' },
      { id = 1111, text = 'SOUNDPROOF' },
      { id = 1112, text = 'EFFECT SPORE' },
      { id = 1113, text = '{PK}RS' },
      { id = 1114, text = 'FIRE' },
      { id = 1115, text = 'FLAME BODY' },
      { id = 1116, text = 'MINUS' },
      { id = 1117, text = 'OWN TEMPO' },
      { id = 1118, text = 'MAGMA ARMOR' },
      { id = 1119, text = 'WATER' },
      { id = 1120, text = 'WATER VEIL' },
      { id = 1121, text = 'BUG' },
      { id = 1122, text = 'SWARM' },
      { id = 1123, text = 'CUTE CHARM' },
      { id = 1124, text = 'IMMUNITY' },
      { id = 1125, text = 'BLAZE' },
      { id = 1126, text = 'PICKUP' },
      { id = 1127, text = 'PATTERN' },
      { id = 1128, text = 'FLASH FIRE' },
      { id = 1129, text = 'VITAL SPIRIT' },
      { id = 1130, text = 'CHLOROPHYLL' },
      { id = 1131, text = 'PURE POWER' },
      { id = 1132, text = 'SHIELD DUST' },
    },
  },
  [3] = {
    id = 3,
    name = 'BATTLE',
    words = {
      { id = 1536, text = 'MATCH UP' },
      { id = 1537, text = 'GO' },
      { id = 1538, text = 'NO. 1' },
      { id = 1539, text = 'DECIDE' },
      { id = 1540, text = 'LET ME WIN' },
      { id = 1541, text = 'WINS' },
      { id = 1542, text = 'WIN' },
      { id = 1543, text = 'WON' },
      { id = 1544, text = 'IF I WIN' },
      { id = 1545, text = 'WHEN I WIN' },
      { id = 1546, text = "CAN'T WIN" },
      { id = 1547, text = 'CAN WIN' },
      { id = 1548, text = 'NO MATCH' },
      { id = 1549, text = 'SPIRIT' },
      { id = 1550, text = 'DECIDED' },
      { id = 1551, text = 'TRUMP CARD' },
      { id = 1552, text = 'TAKE THAT' },
      { id = 1553, text = 'COME ON' },
      { id = 1554, text = 'ATTACK' },
      { id = 1555, text = 'SURRENDER' },
      { id = 1556, text = 'GUTSY' },
      { id = 1557, text = 'TALENT' },
      { id = 1558, text = 'STRATEGY' },
      { id = 1559, text = 'SMITE' },
      { id = 1560, text = 'MATCH' },
      { id = 1561, text = 'VICTORY' },
      { id = 1562, text = 'OFFENSIVE' },
      { id = 1563, text = 'SENSE' },
      { id = 1564, text = 'VERSUS' },
      { id = 1565, text = 'FIGHTS' },
      { id = 1566, text = 'POWER' },
      { id = 1567, text = 'CHALLENGE' },
      { id = 1568, text = 'STRONG' },
      { id = 1569, text = 'TOO STRONG' },
      { id = 1570, text = 'GO EASY' },
      { id = 1571, text = 'FOE' },
      { id = 1572, text = 'GENIUS' },
      { id = 1573, text = 'LEGEND' },
      { id = 1574, text = 'ESCAPE' },
      { id = 1575, text = 'AIM' },
      { id = 1576, text = 'BATTLE' },
      { id = 1577, text = 'FIGHT' },
      { id = 1578, text = 'RESUSCITATE' },
      { id = 1579, text = 'POINTS' },
      { id = 1580, text = 'SERIOUS' },
      { id = 1581, text = 'GIVE UP' },
      { id = 1582, text = 'LOSS' },
      { id = 1583, text = 'IF I LOSE' },
      { id = 1584, text = 'LOST' },
      { id = 1585, text = 'LOSE' },
      { id = 1586, text = 'GUARD' },
      { id = 1587, text = 'PARTNER' },
      { id = 1588, text = 'REJECT' },
      { id = 1589, text = 'ACCEPT' },
      { id = 1590, text = 'INVINCIBLE' },
      { id = 1591, text = 'RECEIVED' },
      { id = 1592, text = 'EASY' },
      { id = 1593, text = 'WEAK' },
      { id = 1594, text = 'TOO WEAK' },
      { id = 1595, text = 'PUSHOVER' },
      { id = 1596, text = 'LEADER' },
      { id = 1597, text = 'RULE' },
      { id = 1598, text = 'MOVE' },
    },
  },
  [4] = {
    id = 4,
    name = 'GREETINGS',
    words = {
      { id = 2048, text = 'THANKS' },
      { id = 2049, text = 'YES' },
      { id = 2050, text = 'HERE GOES' },
      { id = 2051, text = 'HERE I COME' },
      { id = 2052, text = 'HERE IT IS' },
      { id = 2053, text = 'YEAH' },
      { id = 2054, text = 'WELCOME' },
      { id = 2055, text = 'OI' },
      { id = 2056, text = 'HOW DO' },
      { id = 2057, text = 'CONGRATS' },
      { id = 2058, text = 'GIVE ME' },
      { id = 2059, text = 'SORRY' },
      { id = 2060, text = 'APOLOGIZE' },
      { id = 2061, text = 'FORGIVE' },
      { id = 2062, text = 'HEY, THERE' },
      { id = 2063, text = 'HELLO' },
      { id = 2064, text = 'GOOD-BYE' },
      { id = 2065, text = 'THANK YOU' },
      { id = 2066, text = "I'VE ARRIVED" },
      { id = 2067, text = 'PARDON' },
      { id = 2068, text = 'EXCUSE' },
      { id = 2069, text = 'SEE YA' },
      { id = 2070, text = 'EXCUSE ME' },
      { id = 2071, text = 'WELL, THEN' },
      { id = 2072, text = 'GO AHEAD' },
      { id = 2073, text = 'APPRECIATE' },
      { id = 2074, text = 'HEY?' },
      { id = 2075, text = "WHAT'S UP?" },
      { id = 2076, text = 'HUH?' },
      { id = 2077, text = 'NO' },
      { id = 2078, text = 'HI' },
      { id = 2079, text = 'YEAH, YEAH' },
      { id = 2080, text = 'BYE-BYE' },
      { id = 2081, text = 'MEET YOU' },
      { id = 2082, text = 'HEY' },
      { id = 2083, text = 'SMELL' },
      { id = 2084, text = 'LISTENING' },
      { id = 2085, text = 'HOO-HAH' },
      { id = 2086, text = 'YAHOO' },
      { id = 2087, text = 'YO' },
      { id = 2088, text = 'COME OVER' },
      { id = 2089, text = 'COUNT ON' },
    },
  },
  [5] = {
    id = 5,
    name = 'PEOPLE',
    words = {
      { id = 2560, text = 'OPPONENT' },
      { id = 2561, text = 'I' },
      { id = 2562, text = 'YOU' },
      { id = 2563, text = 'YOURS' },
      { id = 2564, text = 'SON' },
      { id = 2565, text = 'YOUR' },
      { id = 2566, text = "YOU'RE" },
      { id = 2567, text = "YOU'VE" },
      { id = 2568, text = 'MOTHER' },
      { id = 2569, text = 'GRANDFATHER' },
      { id = 2570, text = 'UNCLE' },
      { id = 2571, text = 'FATHER' },
      { id = 2572, text = 'BOY' },
      { id = 2573, text = 'ADULT' },
      { id = 2574, text = 'BROTHER' },
      { id = 2575, text = 'SISTER' },
      { id = 2576, text = 'GRANDMOTHER' },
      { id = 2577, text = 'AUNT' },
      { id = 2578, text = 'PARENT' },
      { id = 2579, text = 'MAN' },
      { id = 2580, text = 'ME' },
      { id = 2581, text = 'GIRL' },
      { id = 2582, text = 'BABE' },
      { id = 2583, text = 'FAMILY' },
      { id = 2584, text = 'HER' },
      { id = 2585, text = 'HIM' },
      { id = 2586, text = 'HE' },
      { id = 2587, text = 'PLACE' },
      { id = 2588, text = 'DAUGHTER' },
      { id = 2589, text = 'HIS' },
      { id = 2590, text = "HE'S" },
      { id = 2591, text = "AREN'T" },
      { id = 2592, text = 'SIBLINGS' },
      { id = 2593, text = 'KID' },
      { id = 2594, text = 'CHILDREN' },
      { id = 2595, text = 'MR.' },
      { id = 2596, text = 'MRS.' },
      { id = 2597, text = 'MYSELF' },
      { id = 2598, text = 'I WAS' },
      { id = 2599, text = 'TO ME' },
      { id = 2600, text = 'MY' },
      { id = 2601, text = 'I AM' },
      { id = 2602, text = "I'VE" },
      { id = 2603, text = 'WHO' },
      { id = 2604, text = 'SOMEONE' },
      { id = 2605, text = 'WHO WAS' },
      { id = 2606, text = 'TO WHOM' },
      { id = 2607, text = 'WHOSE' },
      { id = 2608, text = 'WHO IS' },
      { id = 2609, text = "IT'S" },
      { id = 2610, text = 'LADY' },
      { id = 2611, text = 'FRIEND' },
      { id = 2612, text = 'ALLY' },
      { id = 2613, text = 'PERSON' },
      { id = 2614, text = 'DUDE' },
      { id = 2615, text = 'THEY' },
      { id = 2616, text = 'THEY WERE' },
      { id = 2617, text = 'TO THEM' },
      { id = 2618, text = 'THEIR' },
      { id = 2619, text = "THEY'RE" },
      { id = 2620, text = "THEY'VE" },
      { id = 2621, text = 'WE' },
      { id = 2622, text = 'BEEN' },
      { id = 2623, text = 'TO US' },
      { id = 2624, text = 'OUR' },
      { id = 2625, text = "WE'RE" },
      { id = 2626, text = 'RIVAL' },
      { id = 2627, text = "WE'VE" },
      { id = 2628, text = 'WOMAN' },
      { id = 2629, text = 'SHE' },
      { id = 2630, text = 'SHE WAS' },
      { id = 2631, text = 'TO HER' },
      { id = 2632, text = 'HERS' },
      { id = 2633, text = 'SHE IS' },
      { id = 2634, text = 'SOME' },
    },
  },
  [6] = {
    id = 6,
    name = 'VOICES',
    words = {
      { id = 3072, text = '!' },
      { id = 3073, text = '!!' },
      { id = 3074, text = '?!' },
      { id = 3075, text = '?' },
      { id = 3076, text = '…' },
      { id = 3077, text = '…!' },
      { id = 3078, text = '………' },
      { id = 3079, text = '-' },
      { id = 3080, text = '- - -' },
      { id = 3081, text = 'UH-OH' },
      { id = 3082, text = 'WAAAH' },
      { id = 3083, text = 'AHAHA' },
      { id = 3084, text = 'OH?' },
      { id = 3085, text = 'NOPE' },
      { id = 3086, text = 'URGH' },
      { id = 3087, text = 'HMM' },
      { id = 3088, text = 'WHOAH' },
      { id = 3089, text = 'WROOOAAR!' },
      { id = 3090, text = 'WOW' },
      { id = 3091, text = 'GIGGLE' },
      { id = 3092, text = 'SIGH' },
      { id = 3093, text = 'UNBELIEVABLE' },
      { id = 3094, text = 'CRIES' },
      { id = 3095, text = 'AGREE' },
      { id = 3096, text = 'EH?' },
      { id = 3097, text = 'CRY' },
      { id = 3098, text = 'EHEHE' },
      { id = 3099, text = 'OI, OI, OI' },
      { id = 3100, text = 'OH, YEAH' },
      { id = 3101, text = 'OH' },
      { id = 3102, text = 'OOPS' },
      { id = 3103, text = 'SHOCKED' },
      { id = 3104, text = 'EEK' },
      { id = 3105, text = 'GRAAAH' },
      { id = 3106, text = 'GWAHAHAHA' },
      { id = 3107, text = 'WAY' },
      { id = 3108, text = 'TCH' },
      { id = 3109, text = 'HEHE' },
      { id = 3110, text = 'HAH' },
      { id = 3111, text = 'YUP' },
      { id = 3112, text = 'HAHAHA' },
      { id = 3113, text = 'AIYEEH' },
      { id = 3114, text = 'HIYAH' },
      { id = 3115, text = 'FUFUFU' },
      { id = 3116, text = 'LOL' },
      { id = 3117, text = 'SNORT' },
      { id = 3118, text = 'HUMPH' },
      { id = 3119, text = 'HEHEHE' },
      { id = 3120, text = 'HEH' },
      { id = 3121, text = 'HOHOHO' },
      { id = 3122, text = 'UH-HUH' },
      { id = 3123, text = 'OH, DEAR' },
      { id = 3124, text = 'ARRGH' },
      { id = 3125, text = 'MUFUFU' },
      { id = 3126, text = 'MMM' },
      { id = 3127, text = 'OH-KAY' },
      { id = 3128, text = 'OKAY' },
      { id = 3129, text = 'LALALA' },
      { id = 3130, text = 'YAY' },
      { id = 3131, text = 'AWW' },
      { id = 3132, text = 'WOWEE' },
      { id = 3133, text = 'GWAH' },
      { id = 3134, text = 'WAHAHAHA' },
    },
  },
  [7] = {
    id = 7,
    name = 'SPEECH',
    words = {
      { id = 3584, text = 'LISTEN' },
      { id = 3585, text = 'NOT VERY' },
      { id = 3586, text = 'MEAN' },
      { id = 3587, text = 'LIE' },
      { id = 3588, text = 'LAY' },
      { id = 3589, text = 'RECOMMEND' },
      { id = 3590, text = 'NITWIT' },
      { id = 3591, text = 'QUITE' },
      { id = 3592, text = 'FROM' },
      { id = 3593, text = 'FEELING' },
      { id = 3594, text = 'BUT' },
      { id = 3595, text = 'HOWEVER' },
      { id = 3596, text = 'CASE' },
      { id = 3597, text = 'THE' },
      { id = 3598, text = 'MISS' },
      { id = 3599, text = 'HOW' },
      { id = 3600, text = 'HIT' },
      { id = 3601, text = 'ENOUGH' },
      { id = 3602, text = 'A LOT' },
      { id = 3603, text = 'A LITTLE' },
      { id = 3604, text = 'ABSOLUTELY' },
      { id = 3605, text = 'AND' },
      { id = 3606, text = 'ONLY' },
      { id = 3607, text = 'AROUND' },
      { id = 3608, text = 'PROBABLY' },
      { id = 3609, text = 'IF' },
      { id = 3610, text = 'VERY' },
      { id = 3611, text = 'A TINY BIT' },
      { id = 3612, text = 'WILD' },
      { id = 3613, text = "THAT'S" },
      { id = 3614, text = 'JUST' },
      { id = 3615, text = 'EVEN SO,' },
      { id = 3616, text = 'MUST BE' },
      { id = 3617, text = 'NATURALLY' },
      { id = 3618, text = 'FOR NOW,' },
      { id = 3619, text = 'UNDERSTOOD' },
      { id = 3620, text = 'JOKING' },
      { id = 3621, text = 'READY' },
      { id = 3622, text = 'SOMETHING' },
      { id = 3623, text = 'SOMEHOW' },
      { id = 3624, text = 'ALTHOUGH' },
      { id = 3625, text = 'ALSO' },
      { id = 3626, text = 'PERFECT' },
      { id = 3627, text = 'AS MUCH AS' },
      { id = 3628, text = 'REALLY' },
      { id = 3629, text = 'TRULY' },
      { id = 3630, text = 'SERIOUSLY' },
      { id = 3631, text = 'TOTALLY' },
      { id = 3632, text = 'UNTIL' },
      { id = 3633, text = 'AS IF' },
      { id = 3634, text = 'MOOD' },
      { id = 3635, text = 'RATHER' },
      { id = 3636, text = 'AWFULLY' },
      { id = 3637, text = 'MODE' },
      { id = 3638, text = 'MORE' },
      { id = 3639, text = 'TOO LATE' },
      { id = 3640, text = 'FINALLY' },
      { id = 3641, text = 'ANY' },
      { id = 3642, text = 'INSTEAD' },
      { id = 3643, text = 'FANTASTIC' },
    },
  },
  [8] = {
    id = 8,
    name = 'ENDINGS',
    words = {
      { id = 4096, text = 'WILL' },
      { id = 4097, text = 'WILL BE HERE' },
      { id = 4098, text = 'OR' },
      { id = 4099, text = 'TIMES' },
      { id = 4100, text = 'WONDER' },
      { id = 4101, text = 'IS IT?' },
      { id = 4102, text = 'BE' },
      { id = 4103, text = 'GIMME' },
      { id = 4104, text = 'COULD' },
      { id = 4105, text = 'LIKELY TO' },
      { id = 4106, text = 'WOULD' },
      { id = 4107, text = 'IS' },
      { id = 4108, text = "ISN'T IT?" },
      { id = 4109, text = "LET'S" },
      { id = 4110, text = 'OTHER' },
      { id = 4111, text = 'ARE' },
      { id = 4112, text = 'WAS' },
      { id = 4113, text = 'WERE' },
      { id = 4114, text = 'THOSE' },
      { id = 4115, text = "ISN'T" },
      { id = 4116, text = "WON'T" },
      { id = 4117, text = "CAN'T" },
      { id = 4118, text = 'CAN' },
      { id = 4119, text = "DON'T" },
      { id = 4120, text = 'DO' },
      { id = 4121, text = 'DOES' },
      { id = 4122, text = 'WHOM' },
      { id = 4123, text = 'WHICH' },
      { id = 4124, text = "WASN'T" },
      { id = 4125, text = "WEREN'T" },
      { id = 4126, text = 'HAVE' },
      { id = 4127, text = "HAVEN'T" },
      { id = 4128, text = 'A' },
      { id = 4129, text = 'AN' },
      { id = 4130, text = 'NOT' },
      { id = 4131, text = 'THERE' },
      { id = 4132, text = 'OK?' },
      { id = 4133, text = 'SO' },
      { id = 4134, text = 'MAYBE' },
      { id = 4135, text = 'ABOUT' },
      { id = 4136, text = 'OVER' },
      { id = 4137, text = 'IT' },
      { id = 4138, text = 'ALL' },
      { id = 4139, text = 'FOR' },
      { id = 4140, text = 'ON' },
      { id = 4141, text = 'OFF' },
      { id = 4142, text = 'AS' },
      { id = 4143, text = 'TO' },
      { id = 4144, text = 'WITH' },
      { id = 4145, text = 'BETTER' },
      { id = 4146, text = 'EVER' },
      { id = 4147, text = 'SINCE' },
      { id = 4148, text = 'OF' },
      { id = 4149, text = 'BELONGS TO' },
      { id = 4150, text = 'AT' },
      { id = 4151, text = 'IN' },
      { id = 4152, text = 'OUT' },
      { id = 4153, text = 'TOO' },
      { id = 4154, text = 'LIKE' },
      { id = 4155, text = 'DID' },
      { id = 4156, text = "DIDN'T" },
      { id = 4157, text = "DOESN'T" },
      { id = 4158, text = 'WITHOUT' },
      { id = 4159, text = 'AFTER' },
      { id = 4160, text = 'BEFORE' },
      { id = 4161, text = 'WHILE' },
      { id = 4162, text = 'THAN' },
      { id = 4163, text = 'ONCE' },
      { id = 4164, text = 'ANYWHERE' },
    },
  },
  [9] = {
    id = 9,
    name = 'FEELINGS',
    words = {
      { id = 4608, text = 'MEET' },
      { id = 4609, text = 'PLAY' },
      { id = 4610, text = 'HURRIED' },
      { id = 4611, text = 'GOES' },
      { id = 4612, text = 'GIDDY' },
      { id = 4613, text = 'HAPPY' },
      { id = 4614, text = 'HAPPINESS' },
      { id = 4615, text = 'EXCITE' },
      { id = 4616, text = 'IMPORTANT' },
      { id = 4617, text = 'FUNNY' },
      { id = 4618, text = 'GOT' },
      { id = 4619, text = 'GO HOME' },
      { id = 4620, text = 'DISAPPOINTED' },
      { id = 4621, text = 'DISAPPOINTS' },
      { id = 4622, text = 'SAD' },
      { id = 4623, text = 'TRY' },
      { id = 4624, text = 'TRIES' },
      { id = 4625, text = 'HEARS' },
      { id = 4626, text = 'THINK' },
      { id = 4627, text = 'HEAR' },
      { id = 4628, text = 'WANTS' },
      { id = 4629, text = 'MISHEARD' },
      { id = 4630, text = 'DISLIKE' },
      { id = 4631, text = 'ANGRY' },
      { id = 4632, text = 'ANGER' },
      { id = 4633, text = 'SCARY' },
      { id = 4634, text = 'LONESOME' },
      { id = 4635, text = 'DISAPPOINT' },
      { id = 4636, text = 'JOY' },
      { id = 4637, text = 'GETS' },
      { id = 4638, text = 'NEVER' },
      { id = 4639, text = 'DARN' },
      { id = 4640, text = 'DOWNCAST' },
      { id = 4641, text = 'INCREDIBLE' },
      { id = 4642, text = 'LIKES' },
      { id = 4643, text = 'DISLIKES' },
      { id = 4644, text = 'BORING' },
      { id = 4645, text = 'CARE' },
      { id = 4646, text = 'CARES' },
      { id = 4647, text = 'ALL RIGHT' },
      { id = 4648, text = 'ADORE' },
      { id = 4649, text = 'DISASTER' },
      { id = 4650, text = 'ENJOY' },
      { id = 4651, text = 'ENJOYS' },
      { id = 4652, text = 'EAT' },
      { id = 4653, text = 'LACKING' },
      { id = 4654, text = 'BAD' },
      { id = 4655, text = 'HARD' },
      { id = 4656, text = 'TERRIBLE' },
      { id = 4657, text = 'SHOULD' },
      { id = 4658, text = 'NICE' },
      { id = 4659, text = 'DRINK' },
      { id = 4660, text = 'SURPRISE' },
      { id = 4661, text = 'FEAR' },
      { id = 4662, text = 'WANT' },
      { id = 4663, text = 'WAIT' },
      { id = 4664, text = 'SATISFIED' },
      { id = 4665, text = 'SEE' },
      { id = 4666, text = 'RARE' },
      { id = 4667, text = 'NEGATIVE' },
      { id = 4668, text = 'DONE' },
      { id = 4669, text = 'DANGER' },
      { id = 4670, text = 'DEFEATED' },
      { id = 4671, text = 'BEAT' },
      { id = 4672, text = 'GREAT' },
      { id = 4673, text = 'ROMANTIC' },
      { id = 4674, text = 'QUESTION' },
      { id = 4675, text = 'UNDERSTAND' },
      { id = 4676, text = 'UNDERSTANDS' },
    },
  },
  [10] = {
    id = 10,
    name = 'CONDITIONS',
    words = {
      { id = 5120, text = 'HOT' },
      { id = 5121, text = 'EXISTS' },
      { id = 5122, text = 'EXCESS' },
      { id = 5123, text = 'APPROVED' },
      { id = 5124, text = 'HAS' },
      { id = 5125, text = 'GOOD' },
      { id = 5126, text = 'LESS' },
      { id = 5127, text = 'MOMENTUM' },
      { id = 5128, text = 'GOING' },
      { id = 5129, text = 'WEIRD' },
      { id = 5130, text = 'BUSY' },
      { id = 5131, text = 'TOGETHER' },
      { id = 5132, text = 'FULL' },
      { id = 5133, text = 'ABSENT' },
      { id = 5134, text = 'BEING' },
      { id = 5135, text = 'NEED' },
      { id = 5136, text = 'TASTY' },
      { id = 5137, text = 'SKILLED' },
      { id = 5138, text = 'NOISY' },
      { id = 5139, text = 'BIG' },
      { id = 5140, text = 'LATE' },
      { id = 5141, text = 'CLOSE' },
      { id = 5142, text = 'DOCILE' },
      { id = 5143, text = 'AMUSING' },
      { id = 5144, text = 'ENTERTAINING' },
      { id = 5145, text = 'PERFECTION' },
      { id = 5146, text = 'PRETTY' },
      { id = 5147, text = 'HEALTHY' },
      { id = 5148, text = 'EXCELLENT' },
      { id = 5149, text = 'UPSIDE DOWN' },
      { id = 5150, text = 'COLD' },
      { id = 5151, text = 'REFRESHING' },
      { id = 5152, text = 'UNAVOIDABLE' },
      { id = 5153, text = 'MUCH' },
      { id = 5154, text = 'OVERWHELMING' },
      { id = 5155, text = 'FABULOUS' },
      { id = 5156, text = 'ELSE' },
      { id = 5157, text = 'EXPENSIVE' },
      { id = 5158, text = 'CORRECT' },
      { id = 5159, text = 'IMPOSSIBLE' },
      { id = 5160, text = 'SMALL' },
      { id = 5161, text = 'DIFFERENT' },
      { id = 5162, text = 'TIRED' },
      { id = 5163, text = 'SKILL' },
      { id = 5164, text = 'TOP' },
      { id = 5165, text = 'NON-STOP' },
      { id = 5166, text = 'PREPOSTEROUS' },
      { id = 5167, text = 'NONE' },
      { id = 5168, text = 'NOTHING' },
      { id = 5169, text = 'NATURAL' },
      { id = 5170, text = 'BECOMES' },
      { id = 5171, text = 'LUKEWARM' },
      { id = 5172, text = 'FAST' },
      { id = 5173, text = 'LOW' },
      { id = 5174, text = 'AWFUL' },
      { id = 5175, text = 'ALONE' },
      { id = 5176, text = 'BORED' },
      { id = 5177, text = 'SECRET' },
      { id = 5178, text = 'MYSTERY' },
      { id = 5179, text = 'LACKS' },
      { id = 5180, text = 'BEST' },
      { id = 5181, text = 'LOUSY' },
      { id = 5182, text = 'MISTAKE' },
      { id = 5183, text = 'KIND' },
      { id = 5184, text = 'WELL' },
      { id = 5185, text = 'WEAKENED' },
      { id = 5186, text = 'SIMPLE' },
      { id = 5187, text = 'SEEMS' },
      { id = 5188, text = 'BADLY' },
    },
  },
  [11] = {
    id = 11,
    name = 'ACTIONS',
    words = {
      { id = 5632, text = 'MEETS' },
      { id = 5633, text = 'CONCEDE' },
      { id = 5634, text = 'GIVE' },
      { id = 5635, text = 'GIVES' },
      { id = 5636, text = 'PLAYED' },
      { id = 5637, text = 'PLAYS' },
      { id = 5638, text = 'COLLECT' },
      { id = 5639, text = 'WALKING' },
      { id = 5640, text = 'WALKS' },
      { id = 5641, text = 'SAYS' },
      { id = 5642, text = 'WENT' },
      { id = 5643, text = 'SAID' },
      { id = 5644, text = 'WAKE UP' },
      { id = 5645, text = 'WAKES UP' },
      { id = 5646, text = 'ANGERS' },
      { id = 5647, text = 'TEACH' },
      { id = 5648, text = 'TEACHES' },
      { id = 5649, text = 'PLEASE' },
      { id = 5650, text = 'LEARN' },
      { id = 5651, text = 'CHANGE' },
      { id = 5652, text = 'STORY' },
      { id = 5653, text = 'TRUST' },
      { id = 5654, text = 'LAVISH' },
      { id = 5655, text = 'LISTENS' },
      { id = 5656, text = 'HEARING' },
      { id = 5657, text = 'TRAINS' },
      { id = 5658, text = 'CHOOSE' },
      { id = 5659, text = 'COME' },
      { id = 5660, text = 'CAME' },
      { id = 5661, text = 'SEARCH' },
      { id = 5662, text = 'MAKE' },
      { id = 5663, text = 'CAUSE' },
      { id = 5664, text = 'KNOW' },
      { id = 5665, text = 'KNOWS' },
      { id = 5666, text = 'REFUSE' },
      { id = 5667, text = 'STORES' },
      { id = 5668, text = 'BRAG' },
      { id = 5669, text = 'IGNORANT' },
      { id = 5670, text = 'THINKS' },
      { id = 5671, text = 'BELIEVE' },
      { id = 5672, text = 'SLIDE' },
      { id = 5673, text = 'EATS' },
      { id = 5674, text = 'USE' },
      { id = 5675, text = 'USES' },
      { id = 5676, text = 'USING' },
      { id = 5677, text = "COULDN'T" },
      { id = 5678, text = 'CAPABLE' },
      { id = 5679, text = 'DISAPPEAR' },
      { id = 5680, text = 'APPEAR' },
      { id = 5681, text = 'THROW' },
      { id = 5682, text = 'WORRY' },
      { id = 5683, text = 'SLEPT' },
      { id = 5684, text = 'SLEEP' },
      { id = 5685, text = 'RELEASE' },
      { id = 5686, text = 'DRINKS' },
      { id = 5687, text = 'RUNS' },
      { id = 5688, text = 'RUN' },
      { id = 5689, text = 'WORKS' },
      { id = 5690, text = 'WORKING' },
      { id = 5691, text = 'TALKING' },
      { id = 5692, text = 'TALK' },
      { id = 5693, text = 'SINK' },
      { id = 5694, text = 'SMACK' },
      { id = 5695, text = 'PRETEND' },
      { id = 5696, text = 'PRAISE' },
      { id = 5697, text = 'OVERDO' },
      { id = 5698, text = 'SHOW' },
      { id = 5699, text = 'LOOKS' },
      { id = 5700, text = 'SEES' },
      { id = 5701, text = 'SEEK' },
      { id = 5702, text = 'OWN' },
      { id = 5703, text = 'TAKE' },
      { id = 5704, text = 'ALLOW' },
      { id = 5705, text = 'FORGET' },
      { id = 5706, text = 'FORGETS' },
      { id = 5707, text = 'APPEARS' },
      { id = 5708, text = 'FAINT' },
      { id = 5709, text = 'FAINTED' },
    },
  },
  [12] = {
    id = 12,
    name = 'LIFESTYLE',
    words = {
      { id = 6144, text = 'CHORES' },
      { id = 6145, text = 'HOME' },
      { id = 6146, text = 'MONEY' },
      { id = 6147, text = 'ALLOWANCE' },
      { id = 6148, text = 'BATH' },
      { id = 6149, text = 'CONVERSATION' },
      { id = 6150, text = 'SCHOOL' },
      { id = 6151, text = 'COMMEMORATE' },
      { id = 6152, text = 'HABIT' },
      { id = 6153, text = 'GROUP' },
      { id = 6154, text = 'WORD' },
      { id = 6155, text = 'STORE' },
      { id = 6156, text = 'SERVICE' },
      { id = 6157, text = 'WORK' },
      { id = 6158, text = 'SYSTEM' },
      { id = 6159, text = 'TRAIN' },
      { id = 6160, text = 'CLASS' },
      { id = 6161, text = 'LESSONS' },
      { id = 6162, text = 'INFORMATION' },
      { id = 6163, text = 'LIVING' },
      { id = 6164, text = 'TEACHER' },
      { id = 6165, text = 'TOURNAMENT' },
      { id = 6166, text = 'LETTER' },
      { id = 6167, text = 'EVENT' },
      { id = 6168, text = 'DIGITAL' },
      { id = 6169, text = 'TEST' },
      { id = 6170, text = 'DEPT. STORE' },
      { id = 6171, text = 'TELEVISION' },
      { id = 6172, text = 'PHONE' },
      { id = 6173, text = 'ITEM' },
      { id = 6174, text = 'NAME' },
      { id = 6175, text = 'NEWS' },
      { id = 6176, text = 'POPULAR' },
      { id = 6177, text = 'PARTY' },
      { id = 6178, text = 'STUDY' },
      { id = 6179, text = 'MACHINE' },
      { id = 6180, text = 'MAIL' },
      { id = 6181, text = 'MESSAGE' },
      { id = 6182, text = 'PROMISE' },
      { id = 6183, text = 'DREAM' },
      { id = 6184, text = 'KINDERGARTEN' },
      { id = 6185, text = 'LIFE' },
      { id = 6186, text = 'RADIO' },
      { id = 6187, text = 'RENTAL' },
      { id = 6188, text = 'WORLD' },
    },
  },
  [13] = {
    id = 13,
    name = 'HOBBIES',
    words = {
      { id = 6656, text = 'IDOL' },
      { id = 6657, text = 'ANIME' },
      { id = 6658, text = 'SONG' },
      { id = 6659, text = 'MOVIE' },
      { id = 6660, text = 'SWEETS' },
      { id = 6661, text = 'CHAT' },
      { id = 6662, text = "CHILD'S PLAY" },
      { id = 6663, text = 'TOYS' },
      { id = 6664, text = 'MUSIC' },
      { id = 6665, text = 'CARDS' },
      { id = 6666, text = 'SHOPPING' },
      { id = 6667, text = 'CAMERA' },
      { id = 6668, text = 'VIEWING' },
      { id = 6669, text = 'SPECTATOR' },
      { id = 6670, text = 'GOURMET' },
      { id = 6671, text = 'GAME' },
      { id = 6672, text = 'RPG' },
      { id = 6673, text = 'COLLECTION' },
      { id = 6674, text = 'COMPLETE' },
      { id = 6675, text = 'MAGAZINE' },
      { id = 6676, text = 'WALK' },
      { id = 6677, text = 'BIKE' },
      { id = 6678, text = 'HOBBY' },
      { id = 6679, text = 'SPORTS' },
      { id = 6680, text = 'SOFTWARE' },
      { id = 6681, text = 'SONGS' },
      { id = 6682, text = 'DIET' },
      { id = 6683, text = 'TREASURE' },
      { id = 6684, text = 'TRAVEL' },
      { id = 6685, text = 'DANCE' },
      { id = 6686, text = 'CHANNEL' },
      { id = 6687, text = 'MAKING' },
      { id = 6688, text = 'FISHING' },
      { id = 6689, text = 'DATE' },
      { id = 6690, text = 'DESIGN' },
      { id = 6691, text = 'LOCOMOTIVE' },
      { id = 6692, text = 'PLUSH DOLL' },
      { id = 6693, text = 'PC' },
      { id = 6694, text = 'FLOWERS' },
      { id = 6695, text = 'HERO' },
      { id = 6696, text = 'NAP' },
      { id = 6697, text = 'HEROINE' },
      { id = 6698, text = 'FASHION' },
      { id = 6699, text = 'ADVENTURE' },
      { id = 6700, text = 'BOARD' },
      { id = 6701, text = 'BALL' },
      { id = 6702, text = 'BOOK' },
      { id = 6703, text = 'FESTIVAL' },
      { id = 6704, text = 'COMICS' },
      { id = 6705, text = 'HOLIDAY' },
      { id = 6706, text = 'PLANS' },
      { id = 6707, text = 'TRENDY' },
      { id = 6708, text = 'VACATION' },
      { id = 6709, text = 'LOOK' },
    },
  },
  [14] = {
    id = 14,
    name = 'TIME',
    words = {
      { id = 7168, text = 'FALL' },
      { id = 7169, text = 'MORNING' },
      { id = 7170, text = 'TOMORROW' },
      { id = 7171, text = 'LAST' },
      { id = 7172, text = 'DAY' },
      { id = 7173, text = 'SOMETIME' },
      { id = 7174, text = 'ALWAYS' },
      { id = 7175, text = 'CURRENT' },
      { id = 7176, text = 'FOREVER' },
      { id = 7177, text = 'DAYS' },
      { id = 7178, text = 'END' },
      { id = 7179, text = 'TUESDAY' },
      { id = 7180, text = 'YESTERDAY' },
      { id = 7181, text = 'TODAY' },
      { id = 7182, text = 'FRIDAY' },
      { id = 7183, text = 'MONDAY' },
      { id = 7184, text = 'LATER' },
      { id = 7185, text = 'EARLIER' },
      { id = 7186, text = 'ANOTHER' },
      { id = 7187, text = 'TIME' },
      { id = 7188, text = 'FINISH' },
      { id = 7189, text = 'WEDNESDAY' },
      { id = 7190, text = 'SOON' },
      { id = 7191, text = 'START' },
      { id = 7192, text = 'MONTH' },
      { id = 7193, text = 'STOP' },
      { id = 7194, text = 'NOW' },
      { id = 7195, text = 'FINAL' },
      { id = 7196, text = 'NEXT' },
      { id = 7197, text = 'AGE' },
      { id = 7198, text = 'SATURDAY' },
      { id = 7199, text = 'SUMMER' },
      { id = 7200, text = 'SUNDAY' },
      { id = 7201, text = 'BEGINNING' },
      { id = 7202, text = 'SPRING' },
      { id = 7203, text = 'DAYTIME' },
      { id = 7204, text = 'WINTER' },
      { id = 7205, text = 'DAILY' },
      { id = 7206, text = 'OLDEN' },
      { id = 7207, text = 'ALMOST' },
      { id = 7208, text = 'NEARLY' },
      { id = 7209, text = 'THURSDAY' },
      { id = 7210, text = 'NIGHTTIME' },
      { id = 7211, text = 'NIGHT' },
      { id = 7212, text = 'WEEK' },
    },
  },
  [15] = {
    id = 15,
    name = 'MISC.',
    words = {
      { id = 7680, text = 'HIGHS' },
      { id = 7681, text = 'LOWS' },
      { id = 7682, text = 'UM' },
      { id = 7683, text = 'REAR' },
      { id = 7684, text = 'THINGS' },
      { id = 7685, text = 'THING' },
      { id = 7686, text = 'BELOW' },
      { id = 7687, text = 'ABOVE' },
      { id = 7688, text = 'BACK' },
      { id = 7689, text = 'HIGH' },
      { id = 7690, text = 'HERE' },
      { id = 7691, text = 'INSIDE' },
      { id = 7692, text = 'OUTSIDE' },
      { id = 7693, text = 'BESIDE' },
      { id = 7694, text = 'THIS IS IT!' },
      { id = 7695, text = 'THIS' },
      { id = 7696, text = 'EVERY' },
      { id = 7697, text = 'THESE' },
      { id = 7698, text = 'THESE WERE' },
      { id = 7699, text = 'DOWN' },
      { id = 7700, text = 'THAT' },
      { id = 7701, text = 'THOSE ARE' },
      { id = 7702, text = 'THOSE WERE' },
      { id = 7703, text = "THAT'S IT!" },
      { id = 7704, text = 'AM' },
      { id = 7705, text = 'THAT WAS' },
      { id = 7706, text = 'FRONT' },
      { id = 7707, text = 'UP' },
      { id = 7708, text = 'CHOICE' },
      { id = 7709, text = 'FAR' },
      { id = 7710, text = 'AWAY' },
      { id = 7711, text = 'NEAR' },
      { id = 7712, text = 'WHERE' },
      { id = 7713, text = 'WHEN' },
      { id = 7714, text = 'WHAT' },
      { id = 7715, text = 'DEEP' },
      { id = 7716, text = 'SHALLOW' },
      { id = 7717, text = 'WHY' },
      { id = 7718, text = 'CONFUSED' },
      { id = 7719, text = 'OPPOSITE' },
      { id = 7720, text = 'LEFT' },
      { id = 7721, text = 'RIGHT' },
    },
  },
  [16] = {
    id = 16,
    name = 'ADJECTIVES',
    words = {
      { id = 8192, text = 'WANDERING' },
      { id = 8193, text = 'RICKETY' },
      { id = 8194, text = 'ROCK-SOLID' },
      { id = 8195, text = 'HUNGRY' },
      { id = 8196, text = 'TIGHT' },
      { id = 8197, text = 'TICKLISH' },
      { id = 8198, text = 'TWIRLING' },
      { id = 8199, text = 'SPIRALING' },
      { id = 8200, text = 'THIRSTY' },
      { id = 8201, text = 'LOLLING' },
      { id = 8202, text = 'SILKY' },
      { id = 8203, text = 'SADLY' },
      { id = 8204, text = 'HOPELESS' },
      { id = 8205, text = 'USELESS' },
      { id = 8206, text = 'DROOLING' },
      { id = 8207, text = 'EXCITING' },
      { id = 8208, text = 'THICK' },
      { id = 8209, text = 'SMOOTH' },
      { id = 8210, text = 'SLIMY' },
      { id = 8211, text = 'THIN' },
      { id = 8212, text = 'BREAK' },
      { id = 8213, text = 'VORACIOUS' },
      { id = 8214, text = 'SCATTER' },
      { id = 8215, text = 'AWESOME' },
      { id = 8216, text = 'WIMPY' },
      { id = 8217, text = 'WOBBLY' },
      { id = 8218, text = 'SHAKY' },
      { id = 8219, text = 'RIPPED' },
      { id = 8220, text = 'SHREDDED' },
      { id = 8221, text = 'INCREASING' },
      { id = 8222, text = 'YET' },
      { id = 8223, text = 'DESTROYED' },
      { id = 8224, text = 'FIERY' },
      { id = 8225, text = 'LOVEY-DOVEY' },
      { id = 8226, text = 'HAPPILY' },
      { id = 8227, text = 'ANTICIPATION' },
    },
  },
  [17] = {
    id = 17,
    name = 'EVENTS',
    words = {
      { id = 8704, text = 'APPEAL' },
      { id = 8705, text = 'EVENTS' },
      { id = 8706, text = 'STAY-AT-HOME' },
      { id = 8707, text = 'BERRY' },
      { id = 8708, text = 'CONTEST' },
      { id = 8709, text = 'MC' },
      { id = 8710, text = 'JUDGE' },
      { id = 8711, text = 'SUPER' },
      { id = 8712, text = 'STAGE' },
      { id = 8713, text = 'HALL OF FAME' },
      { id = 8714, text = 'EVOLUTION' },
      { id = 8715, text = 'HYPER' },
      { id = 8716, text = 'BATTLE TOWER' },
      { id = 8717, text = 'LEADERS' },
      { id = 8718, text = 'BATTLE ROOM' },
      { id = 8719, text = 'HIDDEN' },
      { id = 8720, text = 'SECRET BASE' },
      { id = 8721, text = 'BLEND' },
      { id = 8722, text = '{POKEBLOCK}' },
      { id = 8723, text = 'MASTER' },
      { id = 8724, text = 'RANK' },
      { id = 8725, text = 'RIBBON' },
      { id = 8726, text = 'CRUSH' },
      { id = 8727, text = 'DIRECT' },
      { id = 8728, text = 'TOWER' },
      { id = 8729, text = 'UNION' },
      { id = 8730, text = 'ROOM' },
      { id = 8731, text = 'WIRELESS' },
    },
  },
  [18] = {
    id = 18,
    name = 'MOVE 1',
    words = {
      { id = 9287, text = 'ABSORB' },
      { id = 9393, text = 'AEROBLAST' },
      { id = 9313, text = 'AGILITY' },
      { id = 9530, text = 'AIR CUTTER' },
      { id = 9462, text = 'ANCIENTPOWER' },
      { id = 9528, text = 'AROMATHERAPY' },
      { id = 9526, text = 'ASTONISH' },
      { id = 9278, text = 'AURORA BEAM' },
      { id = 9333, text = 'BIDE' },
      { id = 9236, text = 'BIND' },
      { id = 9260, text = 'BITE' },
      { id = 9496, text = 'BRICK BREAK' },
      { id = 9361, text = 'BUBBLE' },
      { id = 9484, text = 'CHARGE' },
      { id = 9420, text = 'CHARM' },
      { id = 9344, text = 'CLAMP' },
      { id = 9325, text = 'CONFUSE RAY' },
      { id = 9348, text = 'CONSTRICT' },
      { id = 9538, text = 'COSMIC POWER' },
      { id = 9284, text = 'COUNTER' },
      { id = 9368, text = 'CRABHAMMER' },
      { id = 9454, text = 'CROSS CHOP' },
      { id = 9458, text = 'CRUNCH' },
      { id = 9231, text = 'CUT' },
      { id = 9307, text = 'DIG' },
      { id = 9266, text = 'DISABLE' },
      { id = 9320, text = 'DOUBLE TEAM' },
      { id = 9254, text = 'DOUBLE-EDGE' },
      { id = 9219, text = 'DOUBLESLAP' },
      { id = 9305, text = 'EARTHQUAKE' },
      { id = 9443, text = 'ENCORE' },
      { id = 9499, text = 'ENDEAVOR' },
      { id = 9419, text = 'ENDURE' },
      { id = 9542, text = 'EXTRASENSORY' },
      { id = 9461, text = 'EXTREMESPEED' },
      { id = 9479, text = 'FACADE' },
      { id = 9529, text = 'FAKE TEARS' },
      { id = 9306, text = 'FISSURE' },
      { id = 9391, text = 'FLAIL' },
      { id = 9388, text = 'FLAME WHEEL' },
      { id = 9269, text = 'FLAMETHROWER' },
      { id = 9476, text = 'FLATTER' },
      { id = 9235, text = 'FLY' },
      { id = 9332, text = 'FOCUS ENERGY' },
      { id = 9480, text = 'FOCUS PUNCH' },
      { id = 9482, text = 'FOLLOW ME' },
      { id = 9418, text = 'GIGA DRAIN' },
      { id = 9536, text = 'GRASSWHISTLE' },
      { id = 9290, text = 'GROWTH' },
      { id = 9504, text = 'GRUDGE' },
      { id = 9232, text = 'GUST' },
      { id = 9474, text = 'HAIL' },
      { id = 9322, text = 'HARDEN' },
      { id = 9330, text = 'HAZE' },
      { id = 9245, text = 'HEADBUTT' },
      { id = 9431, text = 'HEAL BELL' },
      { id = 9311, text = 'HYPNOSIS' },
      { id = 9517, text = 'ICE BALL' },
      { id = 9412, text = 'ICY WIND' },
      { id = 9447, text = 'IRON TAIL' },
      { id = 9218, text = 'KARATE CHOP' },
      { id = 9350, text = 'KINESIS' },
      { id = 9357, text = 'LEECH LIFE' },
      { id = 9338, text = 'LICK' },
      { id = 9358, text = 'LOVELY KISS' },
      { id = 9283, text = 'LOW KICK' },
      { id = 9428, text = 'MEAN LOOK' },
      { id = 9478, text = 'MEMENTO' },
      { id = 9535, text = 'METAL SOUND' },
      { id = 9525, text = 'METEOR MASH' },
      { id = 9386, text = 'MIND READER' },
      { id = 9335, text = 'MIRROR MOVE' },
      { id = 9270, text = 'MIST' },
      { id = 9450, text = 'MORNING SUN' },
      { id = 9483, text = 'NATURE POWER' },
      { id = 9387, text = 'NIGHTMARE' },
      { id = 9406, text = 'OCTAZOOKA' },
      { id = 9532, text = 'ODOR SLEUTH' },
      { id = 9416, text = 'OUTRAGE' },
      { id = 9531, text = 'OVERHEAT' },
      { id = 9436, text = 'PAIN SPLIT' },
      { id = 9397, text = 'POWDER SNOW' },
      { id = 9276, text = 'PSYBEAM' },
      { id = 9460, text = 'PSYCH UP' },
      { id = 9310, text = 'PSYCHIC' },
      { id = 9570, text = 'PSYCHO BOOST' },
      { id = 9365, text = 'PSYWAVE' },
      { id = 9444, text = 'PURSUIT' },
      { id = 9315, text = 'RAGE' },
      { id = 9456, text = 'RAIN DANCE' },
      { id = 9445, text = 'RAPID SPIN' },
      { id = 9229, text = 'RAZOR WIND' },
      { id = 9321, text = 'RECOVER' },
      { id = 9432, text = 'RETURN' },
      { id = 9395, text = 'REVERSAL' },
      { id = 9373, text = 'ROCK SLIDE' },
      { id = 9465, text = 'ROCK SMASH' },
      { id = 9304, text = 'ROCK THROW' },
      { id = 9533, text = 'ROCK TOMB' },
      { id = 9421, text = 'ROLLOUT' },
      { id = 9437, text = 'SACRED FIRE' },
      { id = 9435, text = 'SAFEGUARD' },
      { id = 9544, text = 'SAND TOMB' },
      { id = 9244, text = 'SAND-ATTACK' },
      { id = 9417, text = 'SANDSTORM' },
      { id = 9400, text = 'SCARY FACE' },
      { id = 9319, text = 'SCREECH' },
      { id = 9336, text = 'SELFDESTRUCT' },
      { id = 9463, text = 'SHADOW BALL' },
      { id = 9541, text = 'SHADOW PUNCH' },
      { id = 9375, text = 'SHARPEN' },
      { id = 9545, text = 'SHEER COLD' },
      { id = 9540, text = 'SIGNAL BEAM' },
      { id = 9534, text = 'SILVER WIND' },
      { id = 9263, text = 'SING' },
      { id = 9382, text = 'SKETCH' },
      { id = 9501, text = 'SKILL SWAP' },
      { id = 9359, text = 'SKY ATTACK' },
      { id = 9543, text = 'SKY UPPERCUT' },
      { id = 9379, text = 'SLASH' },
      { id = 9481, text = 'SMELLINGSALT' },
      { id = 9339, text = 'SMOG' },
      { id = 9324, text = 'SMOKESCREEN' },
      { id = 9389, text = 'SNORE' },
      { id = 9292, text = 'SOLARBEAM' },
      { id = 9265, text = 'SONICBOOM' },
      { id = 9425, text = 'SPARK' },
      { id = 9385, text = 'SPIDER WEB' },
      { id = 9396, text = 'SPITE' },
      { id = 9363, text = 'SPORE' },
      { id = 9286, text = 'STRENGTH' },
      { id = 9297, text = 'STRING SHOT' },
      { id = 9294, text = 'STUN SPORE' },
      { id = 9282, text = 'SUBMISSION' },
      { id = 9378, text = 'SUPER FANG' },
      { id = 9423, text = 'SWAGGER' },
      { id = 9446, text = 'SWEET SCENT' },
      { id = 9345, text = 'SWIFT' },
      { id = 9451, text = 'SYNTHESIS' },
      { id = 9255, text = 'TAIL WHIP' },
      { id = 9253, text = 'THRASH' },
      { id = 9303, text = 'THUNDER' },
      { id = 9301, text = 'THUNDERBOLT' },
      { id = 9225, text = 'THUNDERPUNCH' },
      { id = 9537, text = 'TICKLE' },
      { id = 9475, text = 'TORMENT' },
      { id = 9469, text = 'UPROAR' },
      { id = 9449, text = 'VITAL THROW' },
      { id = 9539, text = 'WATER SPOUT' },
      { id = 9527, text = 'WEATHER BALL' },
      { id = 9466, text = 'WHIRLPOOL' },
      { id = 9477, text = 'WILL-O-WISP' },
      { id = 9326, text = 'WITHDRAW' },
      { id = 9497, text = 'YAWN' },
    },
  },
  [19] = {
    id = 19,
    name = 'MOVE 2',
    words = {
      { id = 9779, text = 'ACID' },
      { id = 9879, text = 'ACID ARMOR' },
      { id = 10060, text = 'AERIAL ACE' },
      { id = 9861, text = 'AMNESIA' },
      { id = 10020, text = 'ARM THRUST' },
      { id = 10002, text = 'ASSIST' },
      { id = 9941, text = 'ATTRACT' },
      { id = 9868, text = 'BARRAGE' },
      { id = 9840, text = 'BARRIER' },
      { id = 9954, text = 'BATON PASS' },
      { id = 9979, text = 'BEAT UP' },
      { id = 9915, text = 'BELLY DRUM' },
      { id = 10035, text = 'BLAST BURN' },
      { id = 10027, text = 'BLAZE KICK' },
      { id = 9787, text = 'BLIZZARD' },
      { id = 10063, text = 'BLOCK' },
      { id = 9762, text = 'BODY SLAM' },
      { id = 9853, text = 'BONE CLUB' },
      { id = 9926, text = 'BONE RUSH' },
      { id = 9883, text = 'BONEMERANG' },
      { id = 10068, text = 'BOUNCE' },
      { id = 9789, text = 'BUBBLEBEAM' },
      { id = 10067, text = 'BULK UP' },
      { id = 10059, text = 'BULLET SEED' },
      { id = 10075, text = 'CALM MIND' },
      { id = 10021, text = 'CAMOUFLAGE' },
      { id = 9732, text = 'COMET PUNCH' },
      { id = 9821, text = 'CONFUSION' },
      { id = 9888, text = 'CONVERSION' },
      { id = 9904, text = 'CONVERSION 2' },
      { id = 9906, text = 'COTTON SPORE' },
      { id = 10071, text = 'COVET' },
      { id = 10034, text = 'CRUSH CLAW' },
      { id = 9902, text = 'CURSE' },
      { id = 9839, text = 'DEFENSE CURL' },
      { id = 9922, text = 'DESTINY BOND' },
      { id = 9925, text = 'DETECT' },
      { id = 10019, text = 'DIVE' },
      { id = 9874, text = 'DIZZY PUNCH' },
      { id = 10081, text = 'DOOM DESIRE' },
      { id = 9752, text = 'DOUBLE KICK' },
      { id = 10065, text = 'DRAGON CLAW' },
      { id = 10077, text = 'DRAGON DANCE' },
      { id = 9810, text = 'DRAGON RAGE' },
      { id = 9953, text = 'DRAGONBREATH' },
      { id = 9866, text = 'DREAM EATER' },
      { id = 9793, text = 'DRILL PECK' },
      { id = 9951, text = 'DYNAMICPUNCH' },
      { id = 9849, text = 'EGG BOMB' },
      { id = 9780, text = 'EMBER' },
      { id = 10012, text = 'ERUPTION' },
      { id = 9881, text = 'EXPLOSION' },
      { id = 9913, text = 'FAINT ATTACK' },
      { id = 9980, text = 'FAKE OUT' },
      { id = 9934, text = 'FALSE SWIPE' },
      { id = 10025, text = 'FEATHERDANCE' },
      { id = 9854, text = 'FIRE BLAST' },
      { id = 9735, text = 'FIRE PUNCH' },
      { id = 9811, text = 'FIRE SPIN' },
      { id = 9876, text = 'FLASH' },
      { id = 9921, text = 'FORESIGHT' },
      { id = 10066, text = 'FRENZY PLANT' },
      { id = 9946, text = 'FRUSTRATION' },
      { id = 9759, text = 'FURY ATTACK' },
      { id = 9938, text = 'FURY CUTTER' },
      { id = 9882, text = 'FURY SWIPES' },
      { id = 9976, text = 'FUTURE SIGHT' },
      { id = 9865, text = 'GLARE' },
      { id = 9773, text = 'GROWL' },
      { id = 9740, text = 'GUILLOTINE' },
      { id = 9985, text = 'HEAT WAVE' },
      { id = 9998, text = 'HELPING HAND' },
      { id = 9864, text = 'HI JUMP KICK' },
      { id = 9965, text = 'HIDDEN POWER' },
      { id = 9758, text = 'HORN ATTACK' },
      { id = 9760, text = 'HORN DRILL' },
      { id = 10064, text = 'HOWL' },
      { id = 10036, text = 'HYDRO CANNON' },
      { id = 9784, text = 'HYDRO PUMP' },
      { id = 9791, text = 'HYPER BEAM' },
      { id = 9886, text = 'HYPER FANG' },
      { id = 10032, text = 'HYPER VOICE' },
      { id = 9786, text = 'ICE BEAM' },
      { id = 9736, text = 'ICE PUNCH' },
      { id = 10061, text = 'ICICLE SPEAR' },
      { id = 10014, text = 'IMPRISON' },
      { id = 10003, text = 'INGRAIN' },
      { id = 10062, text = 'IRON DEFENSE' },
      { id = 9754, text = 'JUMP KICK' },
      { id = 10010, text = 'KNOCK OFF' },
      { id = 10076, text = 'LEAF BLADE' },
      { id = 9801, text = 'LEECH SEED' },
      { id = 9771, text = 'LEER' },
      { id = 9841, text = 'LIGHT SCREEN' },
      { id = 9927, text = 'LOCK-ON' },
      { id = 10023, text = 'LUSTER PURGE' },
      { id = 9911, text = 'MACH PUNCH' },
      { id = 10005, text = 'MAGIC COAT' },
      { id = 10073, text = 'MAGICAL LEAF' },
      { id = 9950, text = 'MAGNITUDE' },
      { id = 9824, text = 'MEDITATE' },
      { id = 9800, text = 'MEGA DRAIN' },
      { id = 9753, text = 'MEGA KICK' },
      { id = 9733, text = 'MEGA PUNCH' },
      { id = 9952, text = 'MEGAHORN' },
      { id = 9960, text = 'METAL CLAW' },
      { id = 9846, text = 'METRONOME' },
      { id = 9936, text = 'MILK DRINK' },
      { id = 9830, text = 'MIMIC' },
      { id = 9835, text = 'MINIMIZE' },
      { id = 9971, text = 'MIRROR COAT' },
      { id = 10024, text = 'MIST BALL' },
      { id = 9964, text = 'MOONLIGHT' },
      { id = 10069, text = 'MUD SHOT' },
      { id = 10028, text = 'MUD SPORT' },
      { id = 9917, text = 'MUD-SLAP' },
      { id = 10058, text = 'MUDDY WATER' },
      { id = 10030, text = 'NEEDLE ARM' },
      { id = 9829, text = 'NIGHT SHADE' },
      { id = 9734, text = 'PAY DAY' },
      { id = 9792, text = 'PECK' },
      { id = 9923, text = 'PERISH SONG' },
      { id = 9808, text = 'PETAL DANCE' },
      { id = 9770, text = 'PIN MISSILE' },
      { id = 10033, text = 'POISON FANG' },
      { id = 9867, text = 'POISON GAS' },
      { id = 9768, text = 'POISON STING' },
      { id = 10070, text = 'POISON TAIL' },
      { id = 9805, text = 'POISONPOWDER' },
      { id = 9729, text = 'POUND' },
      { id = 9945, text = 'PRESENT' },
      { id = 9910, text = 'PROTECT' },
      { id = 9826, text = 'QUICK ATTACK' },
      { id = 9803, text = 'RAZOR LEAF' },
      { id = 10006, text = 'RECYCLE' },
      { id = 9843, text = 'REFLECT' },
      { id = 10015, text = 'REFRESH' },
      { id = 9884, text = 'REST' },
      { id = 10007, text = 'REVENGE' },
      { id = 9774, text = 'ROAR' },
      { id = 10078, text = 'ROCK BLAST' },
      { id = 10000, text = 'ROLE PLAY' },
      { id = 9755, text = 'ROLLING KICK' },
      { id = 9738, text = 'SCRATCH' },
      { id = 10018, text = 'SECRET POWER' },
      { id = 9797, text = 'SEISMIC TOSS' },
      { id = 10079, text = 'SHOCK WAVE' },
      { id = 9858, text = 'SKULL BASH' },
      { id = 10031, text = 'SLACK OFF' },
      { id = 9749, text = 'SLAM' },
      { id = 9807, text = 'SLEEP POWDER' },
      { id = 9942, text = 'SLEEP TALK' },
      { id = 9852, text = 'SLUDGE' },
      { id = 9916, text = 'SLUDGE BOMB' },
      { id = 10017, text = 'SNATCH' },
      { id = 9863, text = 'SOFTBOILED' },
      { id = 9859, text = 'SPIKE CANNON' },
      { id = 9919, text = 'SPIKES' },
      { id = 9983, text = 'SPIT UP' },
      { id = 9878, text = 'SPLASH' },
      { id = 9939, text = 'STEEL WING' },
      { id = 9982, text = 'STOCKPILE' },
      { id = 9751, text = 'STOMP' },
      { id = 9893, text = 'STRUGGLE' },
      { id = 9892, text = 'SUBSTITUTE' },
      { id = 9969, text = 'SUNNY DAY' },
      { id = 10004, text = 'SUPERPOWER' },
      { id = 9776, text = 'SUPERSONIC' },
      { id = 9785, text = 'SURF' },
      { id = 9984, text = 'SWALLOW' },
      { id = 9914, text = 'SWEET KISS' },
      { id = 9742, text = 'SWORDS DANCE' },
      { id = 9761, text = 'TACKLE' },
      { id = 10022, text = 'TAIL GLOW' },
      { id = 9764, text = 'TAKE DOWN' },
      { id = 9997, text = 'TAUNT' },
      { id = 10026, text = 'TEETER DANCE' },
      { id = 9828, text = 'TELEPORT' },
      { id = 9896, text = 'THIEF' },
      { id = 9814, text = 'THUNDER WAVE' },
      { id = 9812, text = 'THUNDERSHOCK' },
      { id = 9820, text = 'TOXIC' },
      { id = 9872, text = 'TRANSFORM' },
      { id = 9889, text = 'TRI ATTACK' },
      { id = 9999, text = 'TRICK' },
      { id = 9895, text = 'TRIPLE KICK' },
      { id = 9769, text = 'TWINEEDLE' },
      { id = 9967, text = 'TWISTER' },
      { id = 9739, text = 'VICEGRIP' },
      { id = 9750, text = 'VINE WHIP' },
      { id = 10072, text = 'VOLT TACKLE' },
      { id = 9783, text = 'WATER GUN' },
      { id = 10080, text = 'WATER PULSE' },
      { id = 10074, text = 'WATER SPORT' },
      { id = 9855, text = 'WATERFALL' },
      { id = 9746, text = 'WHIRLWIND' },
      { id = 9745, text = 'WING ATTACK' },
      { id = 10001, text = 'WISH' },
      { id = 9763, text = 'WRAP' },
      { id = 9920, text = 'ZAP CANNON' },
    },
  },
  [20] = {
    id = 20,
    name = 'TRENDY SAYING',
    words = {
      { id = 10240, text = 'KTHX, BYE.' },
      { id = 10241, text = 'YES, SIR!' },
      { id = 10242, text = 'AVANT GARDE' },
      { id = 10243, text = 'COUPLE' },
      { id = 10244, text = 'MUCH OBLIGED' },
      { id = 10245, text = 'YEEHAW!' },
      { id = 10246, text = 'MEGA' },
      { id = 10247, text = '1-HIT KO!' },
      { id = 10248, text = 'DESTINY' },
      { id = 10249, text = 'CANCEL' },
      { id = 10250, text = 'NEW' },
      { id = 10251, text = 'FLATTEN' },
      { id = 10252, text = 'KIDDING' },
      { id = 10253, text = 'LOSER' },
      { id = 10254, text = 'LOSING' },
      { id = 10255, text = 'HAPPENING' },
      { id = 10256, text = 'HIP AND' },
      { id = 10257, text = 'SHAKE' },
      { id = 10258, text = 'SHADY' },
      { id = 10259, text = 'UPBEAT' },
      { id = 10260, text = 'MODERN' },
      { id = 10261, text = 'SMELL YA' },
      { id = 10262, text = 'BANG' },
      { id = 10263, text = 'KNOCKOUT' },
      { id = 10264, text = 'HASSLE' },
      { id = 10265, text = 'WINNER' },
      { id = 10266, text = 'FEVER' },
      { id = 10267, text = 'WANNABE' },
      { id = 10268, text = 'BABY' },
      { id = 10269, text = 'HEART' },
      { id = 10270, text = 'OLD' },
      { id = 10271, text = 'YOUNG' },
      { id = 10272, text = 'UGLY' },
    },
  },
  [21] = {
    id = 21,
    name = 'POKéMON (NAT)',
    words = {
      { id = 10815, text = 'ABRA' },
      { id = 11128, text = 'ABSOL' },
      { id = 11136, text = 'AGGRON' },
      { id = 10817, text = 'ALAKAZAM' },
      { id = 11111, text = 'ALTARIA' },
      { id = 11142, text = 'ANORITH' },
      { id = 11143, text = 'ARMALDO' },
      { id = 11134, text = 'ARON' },
      { id = 10936, text = 'AZUMARILL' },
      { id = 11102, text = 'AZURILL' },
      { id = 11147, text = 'BAGON' },
      { id = 11070, text = 'BALTOY' },
      { id = 11130, text = 'BANETTE' },
      { id = 11075, text = 'BARBOACH' },
      { id = 11044, text = 'BEAUTIFLY' },
      { id = 11150, text = 'BELDUM' },
      { id = 10934, text = 'BELLOSSOM' },
      { id = 11034, text = 'BLAZIKEN' },
      { id = 11059, text = 'BRELOOM' },
      { id = 11096, text = 'CACNEA' },
      { id = 11097, text = 'CACTURNE' },
      { id = 11092, text = 'CAMERUPT' },
      { id = 11082, text = 'CARVANHA' },
      { id = 11045, text = 'CASCOON' },
      { id = 11137, text = 'CASTFORM' },
      { id = 11163, text = 'CHIMECHO' },
      { id = 10922, text = 'CHINCHOU' },
      { id = 11125, text = 'CLAMPERL' },
      { id = 11071, text = 'CLAYDOL' },
      { id = 11033, text = 'COMBUSKEN' },
      { id = 11078, text = 'CORPHISH' },
      { id = 10974, text = 'CORSOLA' },
      { id = 11141, text = 'CRADILY' },
      { id = 11079, text = 'CRAWDAUNT' },
      { id = 10921, text = 'CROBAT' },
      { id = 11068, text = 'DELCATTY' },
      { id = 11162, text = 'DEOXYS' },
      { id = 10837, text = 'DODRIO' },
      { id = 10836, text = 'DODUO' },
      { id = 10984, text = 'DONPHAN' },
      { id = 11114, text = 'DUSCLOPS' },
      { id = 11113, text = 'DUSKULL' },
      { id = 11046, text = 'DUSTOX' },
      { id = 11089, text = 'ELECTRIKE' },
      { id = 10853, text = 'ELECTRODE' },
      { id = 11124, text = 'EXPLOUD' },
      { id = 11080, text = 'FEEBAS' },
      { id = 11086, text = 'FLYGON' },
      { id = 11146, text = 'GARDEVOIR' },
      { id = 10826, text = 'GEODUDE' },
      { id = 10955, text = 'GIRAFARIG' },
      { id = 11099, text = 'GLALIE' },
      { id = 10796, text = 'GLOOM' },
      { id = 10794, text = 'GOLBAT' },
      { id = 10870, text = 'GOLDEEN' },
      { id = 10807, text = 'GOLDUCK' },
      { id = 10828, text = 'GOLEM' },
      { id = 11127, text = 'GOREBYSS' },
      { id = 10827, text = 'GRAVELER' },
      { id = 10840, text = 'GRIMER' },
      { id = 11157, text = 'GROUDON' },
      { id = 11030, text = 'GROVYLE' },
      { id = 11104, text = 'GRUMPIG' },
      { id = 11119, text = 'GULPIN' },
      { id = 10882, text = 'GYARADOS' },
      { id = 11088, text = 'HARIYAMA' },
      { id = 10966, text = 'HERACROSS' },
      { id = 10868, text = 'HORSEA' },
      { id = 11126, text = 'HUNTAIL' },
      { id = 10926, text = 'IGGLYBUFF' },
      { id = 11139, text = 'ILLUMISE' },
      { id = 10791, text = 'JIGGLYPUFF' },
      { id = 11161, text = 'JIRACHI' },
      { id = 10816, text = 'KADABRA' },
      { id = 11069, text = 'KECLEON' },
      { id = 10982, text = 'KINGDRA' },
      { id = 11145, text = 'KIRLIA' },
      { id = 10861, text = 'KOFFING' },
      { id = 11156, text = 'KYOGRE' },
      { id = 11135, text = 'LAIRON' },
      { id = 10923, text = 'LANTURN' },
      { id = 11159, text = 'LATIAS' },
      { id = 11160, text = 'LATIOS' },
      { id = 11140, text = 'LILEEP' },
      { id = 11041, text = 'LINOONE' },
      { id = 11048, text = 'LOMBRE' },
      { id = 11047, text = 'LOTAD' },
      { id = 11123, text = 'LOUDRED' },
      { id = 11049, text = 'LUDICOLO' },
      { id = 11100, text = 'LUNATONE' },
      { id = 11077, text = 'LUVDISC' },
      { id = 10820, text = 'MACHAMP' },
      { id = 10819, text = 'MACHOKE' },
      { id = 10818, text = 'MACHOP' },
      { id = 10971, text = 'MAGCARGO' },
      { id = 10881, text = 'MAGIKARP' },
      { id = 10833, text = 'MAGNEMITE' },
      { id = 10834, text = 'MAGNETON' },
      { id = 11087, text = 'MAKUHITA' },
      { id = 11090, text = 'MANECTRIC' },
      { id = 10935, text = 'MARILL' },
      { id = 11036, text = 'MARSHTOMP' },
      { id = 11064, text = 'MASQUERAIN' },
      { id = 11107, text = 'MAWILE' },
      { id = 11109, text = 'MEDICHAM' },
      { id = 11108, text = 'MEDITITE' },
      { id = 11152, text = 'METAGROSS' },
      { id = 11151, text = 'METANG' },
      { id = 11039, text = 'MIGHTYENA' },
      { id = 11081, text = 'MILOTIC' },
      { id = 11106, text = 'MINUN' },
      { id = 11035, text = 'MUDKIP' },
      { id = 10841, text = 'MUK' },
      { id = 10929, text = 'NATU' },
      { id = 11053, text = 'NINCADA' },
      { id = 10790, text = 'NINETALES' },
      { id = 11054, text = 'NINJASK' },
      { id = 11072, text = 'NOSEPASS' },
      { id = 11091, text = 'NUMEL' },
      { id = 11051, text = 'NUZLEAF' },
      { id = 10795, text = 'ODDISH' },
      { id = 11062, text = 'PELIPPER' },
      { id = 10983, text = 'PHANPY' },
      { id = 10924, text = 'PICHU' },
      { id = 10777, text = 'PIKACHU' },
      { id = 10879, text = 'PINSIR' },
      { id = 11105, text = 'PLUSLE' },
      { id = 11038, text = 'POOCHYENA' },
      { id = 10806, text = 'PSYDUCK' },
      { id = 10778, text = 'RAICHU' },
      { id = 11144, text = 'RALTS' },
      { id = 11158, text = 'RAYQUAZA' },
      { id = 11154, text = 'REGICE' },
      { id = 11153, text = 'REGIROCK' },
      { id = 11155, text = 'REGISTEEL' },
      { id = 11133, text = 'RELICANTH' },
      { id = 10864, text = 'RHYDON' },
      { id = 10863, text = 'RHYHORN' },
      { id = 11115, text = 'ROSELIA' },
      { id = 11074, text = 'SABLEYE' },
      { id = 11149, text = 'SALAMENCE' },
      { id = 10779, text = 'SANDSHREW' },
      { id = 10780, text = 'SANDSLASH' },
      { id = 11031, text = 'SCEPTILE' },
      { id = 10869, text = 'SEADRA' },
      { id = 10871, text = 'SEAKING' },
      { id = 11094, text = 'SEALEO' },
      { id = 11050, text = 'SEEDOT' },
      { id = 11131, text = 'SEVIPER' },
      { id = 11083, text = 'SHARPEDO' },
      { id = 11055, text = 'SHEDINJA' },
      { id = 11148, text = 'SHELGON' },
      { id = 11052, text = 'SHIFTRY' },
      { id = 11058, text = 'SHROOMISH' },
      { id = 11129, text = 'SHUPPET' },
      { id = 11043, text = 'SILCOON' },
      { id = 10979, text = 'SKARMORY' },
      { id = 11067, text = 'SKITTY' },
      { id = 11118, text = 'SLAKING' },
      { id = 11116, text = 'SLAKOTH' },
      { id = 10970, text = 'SLUGMA' },
      { id = 11098, text = 'SNORUNT' },
      { id = 11101, text = 'SOLROCK' },
      { id = 11093, text = 'SPHEAL' },
      { id = 11060, text = 'SPINDA' },
      { id = 11103, text = 'SPOINK' },
      { id = 10873, text = 'STARMIE' },
      { id = 10872, text = 'STARYU' },
      { id = 11063, text = 'SURSKIT' },
      { id = 11110, text = 'SWABLU' },
      { id = 11120, text = 'SWALOT' },
      { id = 11037, text = 'SWAMPERT' },
      { id = 11057, text = 'SWELLOW' },
      { id = 11056, text = 'TAILLOW' },
      { id = 10824, text = 'TENTACOOL' },
      { id = 10825, text = 'TENTACRUEL' },
      { id = 11032, text = 'TORCHIC' },
      { id = 11073, text = 'TORKOAL' },
      { id = 11084, text = 'TRAPINCH' },
      { id = 11029, text = 'TREECKO' },
      { id = 11121, text = 'TROPIUS' },
      { id = 11085, text = 'VIBRAVA' },
      { id = 11117, text = 'VIGOROTH' },
      { id = 10797, text = 'VILEPLUME' },
      { id = 11138, text = 'VOLBEAT' },
      { id = 10852, text = 'VOLTORB' },
      { id = 10789, text = 'VULPIX' },
      { id = 11065, text = 'WAILMER' },
      { id = 11066, text = 'WAILORD' },
      { id = 11095, text = 'WALREIN' },
      { id = 10862, text = 'WEEZING' },
      { id = 11076, text = 'WHISCASH' },
      { id = 11122, text = 'WHISMUR' },
      { id = 10792, text = 'WIGGLYTUFF' },
      { id = 11061, text = 'WINGULL' },
      { id = 10954, text = 'WOBBUFFET' },
      { id = 11042, text = 'WURMPLE' },
      { id = 11112, text = 'WYNAUT' },
      { id = 10930, text = 'XATU' },
      { id = 11132, text = 'ZANGOOSE' },
      { id = 11040, text = 'ZIGZAGOON' },
      { id = 10793, text = 'ZUBAT' },
    },
  },
}

local _wordMap = nil

local function buildWordMap()
  if _wordMap then return end
  _wordMap = {}
  for _, group in pairs(EasyChatData.GROUPS) do
    for _, w in ipairs(group.words) do
      _wordMap[w.id] = w.text
    end
  end
end

function EasyChatData.getWord(wordId)
  if not wordId or wordId == EasyChatData.EC_WORD_UNDEFINED then return "" end
  buildWordMap()
  return _wordMap[wordId] or "???"
end

function EasyChatData.decodeWord(wordId)
  if not wordId then return 0, 0 end
  local gid = math.floor(wordId / 512) % 128
  local idx = wordId % 512
  return gid, idx
end

function EasyChatData.encodeWord(groupId, index)
  return ((groupId or 0) % 128) * 512 + ((index or 0) % 512)
end

function EasyChatData.formatPhrase(words, columns, rows)
  words = words or {}
  columns = columns or 2
  rows = rows or 2
  local lines = {}
  local idx = 1
  for r = 1, rows do
    local lineWords = {}
    for c = 1, columns do
      local w = EasyChatData.getWord(words[idx])
      if w and #w > 0 then table.insert(lineWords, w) end
      idx = idx + 1
    end
    table.insert(lines, table.concat(lineWords, " "))
  end
  return table.concat(lines, "\n")
end

return EasyChatData
